### ISSUE TITLE
Unhelpful error message: no file or line number

### ISSUE THREAD

**Issue by MichaelJCole** [pugjs/pug#1165]
Hi, I've tracked an error down to this snippet:

```
doctype 5
html
  head
    title= asdf asdf asdf asdf
```

I think it's the title line.  I get this error:

```
$ jade example.jade                                                                                                                                      
/usr/lib/node_modules/jade/lib/runtime.js:170
  if (!(err instanceof Error)) throw err;
                                     ^
Error
    at new JS_Parse_Error (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:636:9)
    at token_error (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:644:9)
    at expect_token (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:657:9)
    at expect (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:660:36)
    at expr_atom (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:1112:17)
    at maybe_unary (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:1287:19)
    at expr_op (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:1309:33)
    at expr_ops (/usr/lib/node_modules/jade/node_modules/with/node_modules/uglify-js/lib/parse.js:1322:16)
```

I've installed jade 0.34.1 globally

I'm really struggling to use Jade because I'm constantly getting error messages like this that don't reference a line number.  Is there something I'm doing wrong?  How do you get meaningful error messages out of Jade?  Right now, I'm doing a binary search by deleting half the code and recompiling.  It's pretty frustrating.

Thanks!

**Comment by jambalayadog** [comment]
12 years later and this is the silliest decision to obfuscate this information.
