### ISSUE TITLE
Error near line 55, no matter what

### ISSUE THREAD

**Issue by bgotink** [pugjs/pug#1629]
I've got an error near line 55 (sometimes it's line 54, sometimes 56). The error doesn't go away, even when commenting the entire block around it.

The error I originally got:

```
/usr/local/lib/node_modules/jade/lib/runtime.js:202
  throw err;
        ^
Error: export.jade:55
    53|                     span(data-translate-name="copy_text")
    54|                         | Press this button to copy the data to the clipboard, then paste it in a Google Drive Spreadsheet.
  > 55|                 .result-container
    56|                     textarea.result(contenteditable="true", class="export", rows="20")
    57|                 .table-responsive
    58|                     table.result(class="table table-striped table-condensed table-bordered")

Unexpected token `tag` expected `text`, `code`, `:`, `newline` or `eos`
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:805:15)
    at Parser.parseTag (/usr/local/lib/node_modules/jade/lib/parser.js:736:17)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:211:21)
    at Parser.block (/usr/local/lib/node_modules/jade/lib/parser.js:706:25)
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:815:24)
    at Parser.parseTag (/usr/local/lib/node_modules/jade/lib/parser.js:736:17)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:211:21)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:250:21)
    at Parser.block (/usr/local/lib/node_modules/jade/lib/parser.js:706:25)
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:815:24)
```

The error in commented code:

```
/usr/local/lib/node_modules/jade/lib/runtime.js:202
  throw err;
        ^
Error: export.jade:56
    54|             //-             | Press this button to copy the data to the clipboard, then paste it in a Google Drive Spreadsheet.
    55|             //-     .result-container
  > 56|             //-         textarea.result(contenteditable="true", class="export", rows="20")
    57|             //-     .table-responsive
    58|             //-         table.result(class="table table-striped table-condensed table-bordered")
    59|         .modal#modal_parse_export(tabindex="-1", role="dialog", data-backdrop="static", data-keyboard="false", data-show="false", aria-hidden="true", aria-labelled-by="mdl_label_parse_export")

Unexpected token `tag` expected `text`, `code`, `:`, `newline` or `eos`
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:805:15)
    at Parser.parseTag (/usr/local/lib/node_modules/jade/lib/parser.js:736:17)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:211:21)
    at Parser.block (/usr/local/lib/node_modules/jade/lib/parser.js:706:25)
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:815:24)
    at Parser.parseTag (/usr/local/lib/node_modules/jade/lib/parser.js:736:17)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:211:21)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:250:21)
    at Parser.block (/usr/local/lib/node_modules/jade/lib/parser.js:706:25)
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:815:24)
```

When changing a

``` jade
span(lorem=ipsum).
    Some text here
```

into

``` jade
span(lorem=ipsum) Some text here
```

on line 46, the original error moves down one line (to stay on line 55?):

```
/usr/local/lib/node_modules/jade/lib/runtime.js:202
  throw err;
        ^
Error: export.jade:55
    53|                         | Press this button to copy the data to the clipboard, then paste it in a Google Drive Spreadsheet.
    54|                 .result-container
  > 55|                     textarea.result(contenteditable="true", class="export", rows="20")
    56|                 .table-responsive
    57|                     table.result(class="table table-striped table-condensed table-bordered")
    58|         .modal#modal_parse_export(tabindex="-1", role="dialog", data-backdrop="static", data-keyboard="false", data-show="false", aria-hidden="true", aria-labelled-by="mdl_label_parse_export")

Unexpected token `tag` expected `text`, `code`, `:`, `newline` or `eos`
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:805:15)
    at Parser.parseTag (/usr/local/lib/node_modules/jade/lib/parser.js:736:17)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:211:21)
    at Parser.block (/usr/local/lib/node_modules/jade/lib/parser.js:706:25)
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:815:24)
    at Parser.parseTag (/usr/local/lib/node_modules/jade/lib/parser.js:736:17)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:211:21)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:250:21)
    at Parser.block (/usr/local/lib/node_modules/jade/lib/parser.js:706:25)
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:815:24)
```

The code looks like this:

``` jade

mixin container
    .background
    .container
        block

mixin row
    .row
        .col-sm-10.col-sm-offset-1.col-md-8.col-md-offset-2(class!=attributes.class)
            block

+container
    +row
        // ...
    +row.settings
        // ...
    +row
        h2(data-translate-name="result_title") Result
        p
            button#copy(type="button", class="btn btn-default btn-sm", data-translate-name="copy_button").
                Copy
            span(data-translate-name="copy_text")
                | Press this button to copy the data to the clipboard, then paste it in a Google Drive Spreadsheet.
        .result-container
            textarea.result(contenteditable="true", class="export", rows="20")
        .table-responsive
            table.result(class="table table-striped table-condensed table-bordered")
// modal
```

I tried commenting the entire third `+row` in the commented error above.

**Comment by wamoyo** [comment]
I had something similar happening. I had accidentally indented the body tag in my layout.jade so that it was inside the css link tag, but the error, although it had the message right, kept pointing to line 9 in whatever view extended the layout.jade.

**Comment by ForbesLindesay** [comment]
@wamoyo if you still see this error using the latest version of jade, and can provide an example that demonstrates it, I will attempt to fix it.

**Comment by wamoyo** [comment]
@ForbesLindesay Yeah, no problem.

Here's my layout.jade page (The bug might be caused somehow by that 'block head' reference, the real error is the indented body tag):

```
doctype html
html(lang='en')
  head
    meta(charset='utf-8')
    block head
    meta(name='google-site-verification', content='*****')
    meta(name='viewport', content='width=device-width')
    link#favicon(rel='shortcut icon', href='/images/icon.ico')
    link(rel='stylesheet', href='/stylesheets/style.css')
      body
        include header
        block body
        include footer
```

Here's my home.jade page which extends the layout (but really any page I navigate to has the error with a different line references, in truth the extending pages have no error at all):

```
extends layout

block head
  title Innovation Bound
  //- Comment
  meta(name='description', content='description')
  //- Comment
  link(rel="canonical", href='https://domain.com/')

  meta(property='og:title', content='Title of the article')
  meta(property='og:type', content='website')
...

block body
  h1 And so forth...
```

And here's the error:

```
500 Server Error:  Error: /home/path/to/project/views/layout.jade:9
    7|   //- Comment
    8|   link(rel="canonical", href='https://domain.com/')
  > 9| 
    10|   meta(property='og:title', content='Title of the article')
    11|   meta(property='og:type', content='website')
    12|   meta(property='og:image', content='http://media.example.com/1234567.jpg')

link is self closing and should not have content.
```
