### ISSUE TITLE
Stop auto-appending `.pug` to includes/extends

### ISSUE THREAD

**Issue by dizzib** [pugjs/pug#2281]
pug v2.0.0-alpha1
pug-cli v1.0.0-alpha1

For example:

foo.pug

    include _bar
    +bar

_bar.pug

    mixin bar
      .bar

...compiling:

    [andy@kango view (pugfoo)]$ ../../../node_modules/.bin/pug ./foo.pug 

    /home/andy/project/wdts/node_modules/pug/node_modules/pug-runtime/index.js:252
      throw err;
            ^
    TypeError: ./foo.pug:3
        1| include _bar
        2| 
      > 3| +bar
        4| 

    Object #<Object> has no method 'bar'
        at template (eval at wrap (/home/andy/project/wdts/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5:18)
        at renderFile (/home/andy/project/wdts/node_modules/pug-cli/index.js:282:40)
        at /home/andy/project/wdts/node_modules/pug-cli/index.js:146:5
        at Array.forEach (native)
        at Object.<anonymous> (/home/andy/project/wdts/node_modules/pug-cli/index.js:145:9)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)

But if I change foo.pug to include the `.pug` extension...

    include _bar.pug
    +bar

...then compiling works as expected:

    [andy@kango view (pugfoo)]$ ../../../node_modules/.bin/pug ./foo.pug

      rendered foo.html
    [andy@kango view (pugfoo)]$ cat foo.html
    <div class="bar"></div>

This problem does not occur in Jade 1.9.2.

EDIT: Ah, I just saw #2268. In which case shouldn't the error be `ENOENT no such file` since the file `_bar` does not exist ?

**Comment by ForbesLindesay** [comment]
Yes, we were planning to continue appending `.pug` automatically, but in the end we broke support for that when simplifying the distinction between RawIncludes and pug Includes.  We should remove the code that automatically adds `.pug` so as to reduce confusion.

**Comment by ForbesLindesay** [comment]
We now auto-apend .pug still, but it should work properly.
