### ISSUE TITLE
filters not working in includes and extends

### ISSUE THREAD

**Issue by simbo** [pugjs/pug#2287]
I am using pug 2.0.0-alpha1 and tested filter functionality by creating a custom filter at `pug.filters.foo` and additionally by installing `jstranformer-marked`.

Both variants work well when directly used in the rendered file. But as soon as i am using one of them in another file via `include` or `extends`, i get the following error:

```
TypeError: A child of Block (.../foo.pug:6) is of type Filter, which is not supported by pug-code-gen. Please use pug-filters to preprocess this AST.
```

Is this a bug or am i doing something wrong?

**Comment by ForbesLindesay** [comment]
This is a very important bug, thanks for flagging.

**Comment by goodwin64** [comment]
@ForbesLindesay I've got the same error as @simbo.
What should I do exactly?

My console output:
```bash
Starting 'serve'...
App listening on port 3000
TypeError: A child of Block (app/views/test.pug:13) is of type Extends, which is not supported by pug-code-gen. Please use pug-linker to preprocess this AST.
at Object.Compiler.visit 		(node_modules/pug/node_modules/pug-code-gen/index.js:293:13)
at Object.Compiler.visitBlock 	(node_modules/pug/node_modules/pug-code-gen/index.js:383:12)
at Object.Compiler.visitNode 	(node_modules/pug/node_modules/pug-code-gen/index.js:308:37)
at Object.Compiler.visit 		(node_modules/pug/node_modules/pug-code-gen/index.js:296:10)
at Object.Compiler.visitTag 	(node_modules/pug/node_modules/pug-code-gen/index.js:572:12)
at Object.Compiler.visitNode 	(node_modules/pug/node_modules/pug-code-gen/index.js:308:37)
at Object.Compiler.visit 		(node_modules/pug/node_modules/pug-code-gen/index.js:296:10)
at Object.Compiler.visitBlock 	(node_modules/pug/node_modules/pug-code-gen/index.js:383:12)
at Object.Compiler.visitNode 	(node_modules/pug/node_modules/pug-code-gen/index.js:308:37)
at Object.Compiler.visit 		(node_modules/pug/node_modules/pug-code-gen/index.js:296:10)
```

Project structure:
<img src="https://pp.vk.me/c626529/v626529334/1bb63/IIhM4EYEL9o.jpg">
