### ISSUE TITLE
Mixins in includes do not work if included without extension (regression from jade 1.11)

### ISSUE THREAD

**Issue by nkovacs** [pugjs/pug#2308]
create index.pug and index.jade:

```jade
include ./mixins
doctype html
html(lang="en")
    head
        title Leaflet
        +css("http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css")
        +script("http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js")
    body
```

create mixins.pug and mixins.jade:

```jade
mixin css(file, media)
    - media = media || 'all'
    link(type="text/css", rel="stylesheet", media=media, href=file)

mixin script(file)
    script(src=file)
```

install jade-cli and pug-cli

node_modules/.bin/jade --version
```
jade version: 1.11.0
jade-cli version: 0.1.1
```

node_modules/.bin/pug --version
```
pug version: 2.0.0-alpha3
pug-cli version: 1.0.0-alpha1
```

`node_modules/.bin/jade -wP index.jade` works and generates this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Leaflet</title>
    <link type="text/css" rel="stylesheet" media="all" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css"/>
    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
  </head>
  <body></body>
</html>
```

`node_modules/.bin/pug -wP index.pug` does not work:

```
  watching index.pug
  watching mixins.pug
    as a dependency of index.pug
TypeError: index.pug:6
    4|     head
    5|         title Leaflet
  > 6|         +css("http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css")
    7|         +script("http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js")
    8|     body
    9| 

pug_mixins.css is not a function
    at template (eval at wrap (/var/www/jadetest/node_modules/pug-cli/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:18:18)
    at renderFile (/var/www/jadetest/node_modules/pug-cli/index.js:282:40)
    at tryRender (/var/www/jadetest/node_modules/pug-cli/index.js:206:5)
    at /var/www/jadetest/node_modules/pug-cli/index.js:146:5
    at Array.forEach (native)
    at Object.<anonymous> (/var/www/jadetest/node_modules/pug-cli/index.js:145:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by nkovacs** [comment]
It works if I change `include ./mixins` to `include ./mixins.pug`. The bug happens even if mixins.jade does not exist.

**Comment by danielbayley** [comment]
I'm not sure if this info helps, but `include mixins` actually works for me, but _actually_ includes the content in the output, whereas `include mixins.pug` works as expected/intended…
