### ISSUE TITLE
When using "extends" if not specidfied PUG looks for "jade" extension.

### ISSUE THREAD

**Issue by paran0a** [pugjs/pug#2312]
If I have something like 

`extends layout`

I'll get an error

`Error: ENOENT: no such file or directory, open 'C:...\views\layout.jade'`

If I specify that its pug extension like `extends layout.pug` then it works.

**Comment by jeremyrajan** [comment]
👍 , is there a fix for it yet?

**Comment by ForbesLindesay** [comment]
This isn't the behaviour of pug 2.0.0.  I think you're probably using an out of date version.

**Comment by dcollao** [comment]
I have the same error :( Error: ENOENT: no such file or directory, open '/Users/3ndgl0ry/Projects/user-login-system/views/layout.jade'
   at /Users/3ndgl0ry/Projects/user-login-system/views/error.pug line 1
   at Error (native)
   at Object.fs.openSync (fs.js:549:18)
   at Object.fs.readFileSync (fs.js:397:15)
   at Object.load.string.read (/Users/3ndgl0ry/Projects/user-login-system/node_modules/pug/lib/index.js:78:22)
   at Function.read (/Users/3ndgl0ry/Projects/user-login-system/node_modules/pug/node_modules/pug-loader/index.js:66:47)
   at /Users/3ndgl0ry/Projects/user-login-system/node_modules/pug/node_modules/pug-loader/index.js:23:22
   at walkAST (/Users/3ndgl0ry/Projects/user-login-system/node_modules/pug/node_modules/pug-loader/node_modules/pug-walk/index.js:13:26)
   at /Users/3ndgl0ry/Projects/user-login-system/node_modules/pug/node_modules/pug-loader/node_modules/pug-walk/index.js:21:16
   at Array.map (native)
   at walkAST (/Users/3ndgl0ry/Projects/user-login-system/node_modules/pug/node_modules/pug-loader/node_modules/pug-walk/index.js:20:29)

**Comment by ForbesLindesay** [comment]
Please make sure you are using the latest version of pug.

**Comment by jtmdrums** [comment]
Using pug v 3.3.12 on a mac, still getting that error unless I specifically write "extends layout.pug"

**Comment by ForbesLindesay** [comment]
There is no such thing as pug v3.3.12.  The latest version is currently 2.0.0-beta11
