### ISSUE TITLE
Pug SyntaxError: Unexpected token on simple layout

### ISSUE THREAD

**Issue by jforaker** [pugjs/pug#2350]
Just updated to pug. Most pages work except for this one.. any ideas why? (it worked with jade before)

```jade
doctype 5
html(lang='en')
	head
		title Express authentication example
	body
		h1 Sign-in to this Express authentication example
		p Use <i>user</i> for the username and <i>pass</i> for the password.
		form(method='post')
			p
				label(for='username') Username
				input(type='text', name='username')
			p
				label(for='password') Password
				input(type='password', name='password')
			input(type='submit')
		- each message in flash
			h4(style="color: red;") #{message}

```

```
SyntaxError: Unexpected token (42:5)
    at Parser.pp.raise (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn/dist/acorn.js:943:13)
    at Parser.pp.unexpected (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn/dist/acorn.js:1503:8)
    at Parser.pp.semicolon (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn/dist/acorn.js:1482:73)
    at Parser.pp.parseExpressionStatement (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn/dist/acorn.js:1972:8)
    at Parser.pp.parseStatement (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn/dist/acorn.js:1751:188)
    at Parser.pp.parseTopLevel (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parse (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn/dist/acorn.js:1636:17)
    at Object.parse (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn/dist/acorn.js:905:44)
    at reallyParse (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn-globals/index.js:30:18)
    at findGlobals (/Users/jakeforaker/dev/gist-expressauthentication/node_modules/acorn-globals/index.js:45:11)
```

**Comment by jforaker** [comment]
UPDATE: I deleted the `- each` block at the bottom and it rendered without error. Still what is the problem there?

**Comment by TimothyGu** [comment]
Thanks for catching this: it is a conscious decision to disallow this syntax. The reason for this change is that `each` isn't really a JavaScript statement, so we'd have to go through some hacks in the parser to support using `each` as part of unbuffered code `-`.

To fix this it's very simple: removing <code>-&nbsp;</code> before the `each` and it should work fine again.

For other incompatible changes in Pug 2 check #2305. Many incompatibilities are already warned against in Jade 1.

Good luck!

**Comment by jforaker** [comment]
Yes, I can confirm that removing the `-` before the `each` does the trick. Keep up the good work!
