### ISSUE TITLE
TypeError: Cannot assign to read only property 'cwd' of !**/_*.pug

### ISSUE THREAD

**Issue by theskillwithin** [pugjs/pug#2366]
[17:47:47] 'pug' errored after 342 μs
[17:47:47] TypeError: Cannot assign to read only property 'cwd' of !src/**/_*.pug
    at Object.gs.createStream (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/index.js:19:46)
    at Object.gs.create (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/index.js:68:42)
    at Gulp.src (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.<anonymous> (/Users/Austin/Projects/heartcup/gulpfile.js:32:14)
    at module.exports (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/Users/Austin/Projects/heartcup/node_modules/gulp/index.js:36:18)
    at Gaze.<anonymous> (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:18:14)

```
gulp.task('pug', function() {
        gulp.src('src/**/*.pug','!src/**/_*.pug')
        .pipe(pug()) // pip to jade plugin
        .pipe(gulp.dest('src')); // tell gulp our output folder
});


gulp.watch('src/*.pug',['pug']);
```

**Comment by TimothyGu** [comment]
That's a gulp-pug bug.
