### ISSUE TITLE
Include producing TypeError

### ISSUE THREAD

**Issue by rmoore74** [pugjs/pug#2373]
When trying to include basic header.pug into header of main pug view, a TypeError referencing that it cannot read the property type 'replace' of 'undefined' occurs.

**header.pug**
```
head
    title= title
    link(rel='stylesheet', href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
    script(src='https://code.jquery.com/jquery-2.2.3.min.js')
    script(src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
    style(type='text/css').
        .form-container {
            width: 400px;
            margin: auto;
        }
```
**index.pug**
```
doctype html
html
    include ./partials/header.pug
    body
```

Error returned:
```
TypeError: Cannot read property 'replace' of undefined
   at before (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/index.js:104:48)
   at walkAST (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:13:26)
   at /home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:21:16
   at Array.map (native)
   at walkAST (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:20:29)
   at walkAST (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:33:21)
   at /home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:21:16
   at Array.map (native)
   at walkAST (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:20:29)
   at applyIncludes (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/index.js:102:10)
   at link (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/index.js:21:9)
   at compileBody (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:84:11)
   at Object.exports.compile (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:164:16)
   at handleTemplateCache (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:137:25)
   at Object.exports.renderFile (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:331:10)
   at Object.exports.renderFile (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:321:21) 
```

When using latest version of Jade include works like normal and without error.

**Comment by ForbesLindesay** [comment]
Could you provide the stack trace as well as the error please?  It may be caused by the include path being `.jade` when it should be `.pug` but if the type error is in pug's code I'd still like to track down why we didn't provide a proper error.

**Comment by rmoore74** [comment]
Oops, my bad. I copied and pasted that excerpt after I had changed it to '.jade'. Before that it was '.pug'. I shall edit that in the original post. 

Of course - here is the stack trace and error (using '.pug' extension): 
```
TypeError: Cannot read property 'replace' of undefined
   at before (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/index.js:104:48)
   at walkAST (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:13:26)
   at /home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:21:16
   at Array.map (native)
   at walkAST (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:20:29)
   at walkAST (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:33:21)
   at /home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:21:16
   at Array.map (native)
   at walkAST (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:20:29)
   at applyIncludes (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/index.js:102:10)
   at link (/home/rmoore74/node-projects/pug-test/node_modules/pug/node_modules/pug-linker/index.js:21:9)
   at compileBody (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:84:11)
   at Object.exports.compile (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:164:16)
   at handleTemplateCache (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:137:25)
   at Object.exports.renderFile (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:331:10)
   at Object.exports.renderFile (/home/rmoore74/node-projects/pug-test/node_modules/pug/lib/index.js:321:21) 
```

**Comment by ForbesLindesay** [comment]
Also, can you confirm what version of pug you're using?

**Comment by ForbesLindesay** [comment]
It doesn't look (based on the line number) like pug-alpha7.  Please confirm that this still reproduces on pug-alpha7.

**Comment by rmoore74** [comment]
Ah, there lies the problem. All working now. Sorry!
