### ISSUE TITLE
ES6 code in includes causes syntax error

### ISSUE THREAD

**Issue by mrchief** [pugjs/pug#2401]
Banging my head on this for hours now, can't figure out what's wrong:

Here's my setup:

```
|   _layout.pug
|   
+---docs
|   |  index.md
|               
+---support
|   |  index.pug
|       
\---_shared
    |  _icons.pug              
```

**_layout.pug**

```jade
doctype html

html.no-js
  head
  
  include _shared/_icons

  body
    block content
      article.main-container
        != article
```

**shared/_icons.pug**

```jade
- var baseUrl = 'http://domain.com/assets/img'

each val in [57, 60, 72, 76, 114, 120, 144, 152, 180]
  link(rel='apple-touch-icon', sizes=`${val}x${val}`, href=`${baseUrl}/apple-touch-icon-${val}x${val}.png`)

```

**support/index.pug**

```jade
extends ../_layout.pug

block content
  h1 Support
  p We want to hear from you. 
```

**docs/index.md**

```md
# Hello world!

We come in peace!
```

I'm compiling and rendering the files like this:

**docs/index.md**

```js
// after rendering markdown via marked js

var fn = pug.compileFile('_layout.pug', {
  pretty: true
});

var locals = {
  article = <rendered markdown string>
};

var html = fn(locals);
```

**support/index.pug**

```js
var fn = pug.compileFile('support/index.pug', {
  pretty: true
});

var html = fn({});
```

Now `index.pug` renders without any issues. However, `index.md` throws:

```
c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:1747
  throw err;
  ^

SyntaxError: Unexpected token (1:40)
    at Parser.pp.raise (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:1745:13)
    at Parser.pp.unexpected (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:2264:8)
    at Parser.pp.parseBindingAtom (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:1876:12)
    at Parser.pp.parseMaybeDefault (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:1920:23)
    at Parser.pp.parseBindingList (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:1896:23)
    at Parser.pp.parseFunctionParams (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:2776:22)
    at Parser.pp.parseFunction (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:2769:8)
    at Parser.pp.parseExprAtom (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:1129:19)
    at Parser.pp.parseExprSubscripts (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:1023:19)
    at Parser.pp.parseMaybeUnary (c:\workspace\jadeTest\node_modules\with\node_modules\acorn\dist\acorn.js:1004:19)
```

If I take off backticks from `_icons.pug`, this error goes away. I'm not sure why it throws this error in case of rendering `_layout.pug` but not in case of `support/index.pug`.

I've tried removing md file and instead setting a plain text value but the error still happens (so markdown rendering is not affecting it). Any ideas?

Using version `^2.0.0-alpha6`

**Comment by mrchief** [comment]
Found it! In some places, I was using `!= yield`. `yield` works as long as backticks are not present. Is this because `yield` is a reserved keyword and having backticks enables ES6 mode thus causing `yield` to become an issue?

This issue can be closed otherwise.

**Comment by TimothyGu** [comment]
> Is this because `yield` is a reserved keyword and having backticks enables ES6 mode thus causing `yield` to become an issue?

Yes, although it is kind of also a bug that you didn't see an enhanced error message pointing out which Pug file and line causes the hard-to-debug error.

**Comment by mrchief** [comment]
Also, I'm not sure why `yield` is fine if not used in conjunction with any ES6 features. I tried looking into source but was too time-pressured to make sense of anything. 

Feel free to close this or re-edit this (since I get a sense that you would like to improvise the error handling).

**Comment by TimothyGu** [comment]
Okay, I believe that `yield` is not an error because there's a compat layer in the ES2015 spec that allows the use of the keyword as an identifier (so that old code using `var yield` still work). However, expressions like `yield myVal` was invalid under ES5, and they cause an error in parsing.

**Comment by niftylettuce** [comment]
The backtics did it for me, won't run in non ES6 browsers like Firefox 35 and older versions of Safari.
