### ISSUE TITLE
Includes not working

### ISSUE THREAD

**Issue by Pratinav** [pugjs/pug#2411]
Hi,

I am working on a Node JS project with Express and pug as my view engine.
My directory structure is-
```
├── index.js
├── public
│   ├── css
│   │   └── main.css
│   └── js
│       └── app.js
└── views
    ├── index.pug
    └── layout.pug
```

My index.pug has the following contents-
```
extends layout.pug
...
style
    include ../public/css/main.css
...
```

But it gives me this error-
```
TypeError: Cannot read property 'replace' of undefined
    at before (/Users/pratinavbagla/Documents/web-projects/pole-chat/node_modules/pug-linker/index.js:104:48)
    at walkAST (/Users/pratinavbagla/Documents/web-projects/pole-chat/node_modules/pug-walk/index.js:13:26)
    at /Users/pratinavbagla/Documents/web-projects/pole-chat/node_modules/pug-walk/index.js:21:16
    at Array.map (native)
    at walkAST (/Users/pratinavbagla/Documents/web-projects/pole-chat/node_modules/pug-walk/index.js:20:29)
    at /Users/pratinavbagla/Documents/web-projects/pole-chat/node_modules/pug-walk/index.js:21:16
    at Array.map (native)
    at walkAST (/Users/pratinavbagla/Documents/web-projects/pole-chat/node_modules/pug-walk/index.js:20:29)
    at applyIncludes (/Users/pratinavbagla/Documents/web-projects/pole-chat/node_modules/pug-linker/index.js:102:10)
    at link (/Users/pratinavbagla/Documents/web-projects/pole-chat/node_modules/pug-linker/index.js:21:9)
```

**HALP**

**Comment by ForbesLindesay** [comment]
That seems odd.  Can you confirm what version of pug you are using?

**Comment by Pratinav** [comment]
```
├─┬ pug@0.1.0
│ ├─┬ pug-code-gen@0.0.0
│ │ ├─┬ constantinople@3.0.2
│ │ │ └── acorn@2.7.0
│ │ ├── doctypes@1.0.0
│ │ ├── js-stringify@1.0.2
│ │ ├── pug-attrs@0.0.0
│ │ ├── void-elements@2.0.1
│ │ └─┬ with@5.0.0
│ │   ├── acorn@1.2.2
│ │   └── acorn-globals@1.0.9
│ ├─┬ pug-filters@1.1.0
│ │ ├─┬ clean-css@3.4.15
│ │ │ ├─┬ commander@2.8.1
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ └─┬ source-map@0.4.4
│ │ │   └── amdefine@1.0.0
│ │ ├─┬ jstransformer@0.0.3
│ │ │ ├── is-promise@2.1.0
│ │ │ └─┬ promise@7.1.1
│ │ │   └── asap@2.0.4
│ │ ├── pug-error@0.0.0
│ │ ├── pug-walk@0.0.0
│ │ ├── resolve@1.1.7
│ │ └─┬ uglify-js@2.6.2
│ │   ├── async@0.2.10
│ │   ├── source-map@0.5.6
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.10.0
│ │     ├── camelcase@1.2.1
│ │     ├─┬ cliui@2.1.0
│ │     │ ├─┬ center-align@0.1.3
│ │     │ │ ├─┬ align-text@0.1.4
│ │     │ │ │ ├─┬ kind-of@3.0.3
│ │     │ │ │ │ └── is-buffer@1.1.3
│ │     │ │ │ ├── longest@1.0.1
│ │     │ │ │ └── repeat-string@1.5.4
│ │     │ │ └── lazy-cache@1.0.4
│ │     │ ├── right-align@0.1.3
│ │     │ └── wordwrap@0.0.2
│ │     ├── decamelize@1.2.0
│ │     └── window-size@0.1.0
│ ├─┬ pug-lexer@0.0.0
│ │ ├─┬ character-parser@2.2.0
│ │ │ └── is-regex@1.0.3
│ │ └─┬ is-expression@1.0.2
│ │   └── object-assign@4.1.0
│ ├── pug-linker@0.0.0
│ ├── pug-loader@0.0.0
│ ├─┬ pug-parser@0.0.0
│ │ └── token-stream@0.0.1
│ ├── pug-runtime@0.0.0
│ └── pug-strip-comments@0.0.1
```

**Comment by ForbesLindesay** [comment]
You need to install the latest version of pug, currently 
2.0.0-beta2
