### ISSUE TITLE
":" is not valid as the start or end of an un-quoted attribute.

### ISSUE THREAD

**Issue by enlore** [pugjs/pug#2454]
Hey all. I'm working with Pug to create Vue templates. Vue enables the use of `:` prefixed attribute names as a shorthand for binding attribute values to properties on instances of Vue powered view-model objects.

For example:

    <template lang="pug">
        #component-root
            // here's the full syntax for a style attribute bound to an object
            // it works just fine
            h1(v-bind:style="styleObject") {{ h1Content }}

            // here's the shorthand of the binding syntax
            // it breaks
            h1(:style="styleObject") {{ h1Content }}

            // here's a couple of tweaked versions of the same pug code that work fine
            h1( :style="styleObject") {{ h1Content }}
            //  ^ note the whitespace

            h1(,:style="styleObject") {{ h1Content }}
            // this one is cool because of the prefixed comma, as though this were one of several attributes
    </template>

    <script>
         var vm = new Vue({
             template: "#this-template",
             data: { 
                 styleObject: { "font-size": "60px", "text-transform": "uppercase" },
                 h1Content: "bark bark bark bark bark!"
             }
         });
    </script>

Ultimately, this should render down to something like the following html:

    <div id="component-root">
        <h1 style="font-size: 60px; text-transform: uppercase;"> bark bark bark bark bark! </h1>
    </div>

My efforts are being built out by a browserify transform (vueify) that uses Pug to do the template compilation. It happens with `v0.1.0` and `v2.0.0-beta3`. Here's the error generated by the build:

```

Error: Pug:3:15
    1|
    2| #app-root
  > 3|   h1(:style="styles") {{ msg }}
---------------------^
    4|   p {{ blob }}
    5|
    6|   app-nav

":" is not valid as the start or end of an un-quoted attribute. while parsing file: /Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/src/App.vue
    1|
    2| #app-root
  > 3|   h1(:style="styles") {{ msg }}
---------------------^
    4|   p {{ blob }}
    5|
    6|   app-nav

":" is not valid as the start or end of an un-quoted attribute. while parsing file: /Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/src/App.vue
    at makeError (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/node_modules/pug-lexer/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/node_modules/pug-lexer/index.js:58:15)
    at Lexer.attrs (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/node_modules/pug-lexer/index.js:1072:18)
    at Lexer.callLexerFunction (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/node_modules/pug-lexer/index.js:1298:23)
    at Lexer.advance (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/node_modules/pug-lexer/index.js:1335:15)
    at Lexer.callLexerFunction (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/node_modules/pug-lexer/index.js:1298:23)
    at Lexer.getTokens (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/node_modules/pug-lexer/index.js:1354:12)
    at lex (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/node_modules/pug-lexer/index.js:12:42)
    at Object.load.string.lex (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/lib/index.js:94:27)
    at Function.loadString [as string] (/Users/mqi7918/projects/code/elcg_clients/bitharbor.us/alt_client/node_modules/pug/node_modules/pug-load/index.js:45:24)
```

Same biz happens independent of framework/build:

```
15:44:09 › pug --version
pug version: 2.0.0-beta3
pug-cli version: 1.0.0-alpha6

15:44:25 › pug wee.pug

/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-lexer/index.js:59
    throw err;
    ^

Error: wee.pug:1:10
  > 1| h1(:bark="woo")  BARK BARK BARK
----------------^
    2|

":" is not valid as the start or end of an un-quoted attribute.
    at makeError (/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-lexer/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-lexer/index.js:58:15)
    at Lexer.attrs (/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-lexer/index.js:1072:18)
    at Lexer.callLexerFunction (/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-lexer/index.js:1298:23)
    at Lexer.advance (/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-lexer/index.js:1335:15)
    at Lexer.callLexerFunction (/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-lexer/index.js:1298:23)
    at Lexer.getTokens (/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-lexer/index.js:1354:12)
    at lex (/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-lexer/index.js:12:42)
    at Object.load.string.lex (/usr/local/lib/node_modules/pug-cli/node_modules/pug/lib/index.js:94:27)
    at Function.loadString [as string] (/usr/local/lib/node_modules/pug-cli/node_modules/pug/node_modules/pug-load/index.js:45:24)
```

**Comment by TimothyGu** [comment]
@ForbesLindesay, I am inclined to revert the change that disallows this. The syntax isn't disallowed in the HTML spec or any other standard, and it's used by a major framework. Plus, many people have complained about this issue.

**Comment by ForbesLindesay** [comment]
OK, lets revert it

**Comment by bkuri** [comment]
@ForbesLindesay I keep getting this error as of v2.0.0-beta6, which is the current version used in CodePen. It seems to be fine if I use it as the first attribute, but breaks every other time. Here's a pen for you to check out: https://codepen.io/bkuri/pen/RKJRxV?editors=1000

As you can see, if you remove the `v-bind` on line 8 you will get a `Syntax Error: Unexpected token` error. You can also replicate this by removing the second or third `v-bind` directives on lines 12 and/or 13, but not the one on line 11.

Here's a screenshot of the first error:
![screenshot at 15-25-31](https://cloud.githubusercontent.com/assets/138886/22621654/2e8758f8-eaee-11e6-8fef-4d5ce457e73f.png)

**Comment by enlore** [comment]
You're missing a comma between the arguments to the `el-button` element.

`el-button(type='primary' :loading='true') Test`

should be

`el-button(type='primary', :loading='true') Test`

**Comment by bkuri** [comment]
@enlore adding commas is a valid (albeit a bit ugly) workaround:
![screenshot at 19-45-55](https://cloud.githubusercontent.com/assets/138886/22623035/aa44dc8a-eb12-11e6-821e-b0e0eedf20be.png)

I guess I'll do that for now. :+1:

**Comment by TimothyGu** [comment]
@bkuri, the recommended way is to quote your attributes, like 

```pug
el-pagination(layout="prev, pager, next" ":current-page"="5" ":page-size"="100" ":total"="1000")
```

This way, you can avoid using the admittedly ugly commas.

**Comment by bkuri** [comment]
@TimothyGu that makes sense, although I do still think it's worth fixing at some point, considering that the Vue shorthands just work™ when using plain HTML.

**Comment by edjroot** [comment]
Quoted attributes look much more confusing than commas. Still, commas being optional would be great.

**Comment by mccxiv** [comment]
Not quite sure why this issue is closed. Why's the comma workaround still necessary?

**Comment by qm3ster** [comment]
@mccxiv it was committed to master on Feb 8 and the last release was on Feb 4.
It needs to be pushed to npm. But master is currently failing: #2713
Just do https://github.com/pugjs/pug/commit/6b6e4584c6787972ce5a4c2dec3ccf4aa3767e57 for now.
