### ISSUE TITLE
Not recognizing spaces in directory when runing pug --watch [dir]

### ISSUE THREAD

**Issue by poncianodiego** [pugjs/pug#2519]
So I am trying to run pug watch -- after installing successfully but when I run it, it tells me it could not find the project (my name has a space):

C:\Users\Juan Diego\Desktop\Websites\VAHO>pug --watch C:\Users\Juan Diego\Desktop\Websites\VAHO

Error: ENOENT: no such file or directory, lstat 'C:\Users\Juan'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at renderFile (C:\Users\Juan Diego\AppData\Roaming\npm\node_modules\pug-cli\index.js:246:17)
    at tryRender (C:\Users\Juan Diego\AppData\Roaming\npm\node_modules\pug-cli\index.js:209:5)
    at C:\Users\Juan Diego\AppData\Roaming\npm\node_modules\pug-cli\index.js:149:5
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\Juan Diego\AppData\Roaming\npm\node_modules\pug-cli\index.js:148:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
Error: ENOENT: no such file or directory, lstat 'C:\Users\Juan Diego\Desktop\Websites\VAHO\Diego\Desktop\Websites\VAHO'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at renderFile (C:\Users\Juan Diego\AppData\Roaming\npm\node_modules\pug-cli\index.js:246:17)
    at tryRender (C:\Users\Juan Diego\AppData\Roaming\npm\node_modules\pug-cli\index.js:209:5)
    at C:\Users\Juan Diego\AppData\Roaming\npm\node_modules\pug-cli\index.js:149:5
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\Juan Diego\AppData\Roaming\npm\node_modules\pug-cli\index.js:148:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

Will I need to change my user name in windows?? 

Thanks.

**Comment by ecbftw** [comment]
Have you tried this instead?
`pug --watch "C:\Users\Juan Diego\Desktop\Websites\VAHO"`

**Comment by poncianodiego** [comment]
That worked! Thanks

**Comment by avalanche1** [comment]
I think this sd be reopened and fixed in the cli.
