### ISSUE TITLE
Compiling a file via standard in breaks with extends

### ISSUE THREAD

**Issue by robbyoconnor** [pugjs/pug#2536]
$ pug < pug-extends.pug 
```
/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:26
          throw ex;
          ^

Error: the "filename" option is required to use includes and extends with "relative" paths
    at undefined line 1
    at Function.resolve (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:59:11)
    at load.string.resolve (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug/lib/index.js:131:19)
    at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:21:51
    at walkAST (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-walk/index.js:13:26)
    at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-walk/index.js:21:16
    at Array.map (native)
    at walkAST (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-walk/index.js:20:29)
    at load (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:12:10)
    at Function.loadString [as string] (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:47:10)
    at compileBody (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug/lib/index.js:81:18)
```
If I don't use stdin:

$ pug pug-extends.pug 
```
  rendered pug-extends.html
```

The pug templates

#pug-base.pug
```jade
doctype html
html
  head
    title Pug Example with extends

    body
      h1 Something, something, something

      block content
```

# pug-extends.pug
```jade
extends pug-base.pug
block content
  h2 This is content

```

**Comment by TimothyGu** [comment]
Resolving paths for `extend`s requires knowledge of the path of the file containing the `extends`. It is impossible to get this information with stdin. You can work around this by using the `-p, --path` option in pug-cli.

**Comment by robbyoconnor** [comment]
Okay, thanks for the fast response, good to have this issue anyways :)
