### ISSUE TITLE
pug looking in wrong directory despite being passed a path (via -p) and basedir (via -b) when using standard in to feed the file to pug. It seems to be one-level off in almost all cases

### ISSUE THREAD

**Issue by robbyoconnor** [pugjs/pug#2539]
```
$ pug -b /home/rob/pug/foo/bar/baz -p /home/rob/pug/foo/bar/baz < /home/rob/pug/foo/bar/baz/pug-extends.pug
/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:26
          throw ex;
          ^

Error: ENOENT: no such file or directory, open '/home/rob/pug/foo/bar/pug-baseeeeeee.pug'
    at /home/rob/pug/foo/bar/baz line 1
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Function.read (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:69:13)
    at load.string.read (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug/lib/index.js:142:25)
    at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:23:44
    at walkAST (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-walk/index.js:13:26)
    at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-walk/index.js:21:16
    at Array.map (native)
    at walkAST (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-walk/index.js:20:29)`
```

Specifically why is it not in the right directory, I passed in `~/pug/foo/bar/baz`, yet it's looking in `~/pug/foo/bar/`

This only shows up when passing the files via standard in...this has to be a bug...

**Comment by TimothyGu** [comment]
`-p`'s help message is "filename used to resolve includes." You are supposed to put the file name of the Pug template, as you are with the `filename` option.

**Comment by robbyoconnor** [comment]
what does that mean though?

**Comment by robbyoconnor** [comment]
the filename of the file being passed?

**Comment by TimothyGu** [comment]
Yes

**Comment by robbyoconnor** [comment]
That fixed it 

```
$ pug -b /home/rob/pug/foo/bar/baz -p /home/rob/pug/foo/bar/baz/pug-extends.pug < /home/rob/pug/foo/bar/baz/pug-extends.pug
/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:26
          throw ex;
          ^

Error: ENOENT: no such file or directory, open '/home/rob/pug/foo/bar/baz/pug-baseeeeeee.pug'
    at /home/rob/pug/foo/bar/baz/pug-extends.pug line 1
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Function.read (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:69:13)
    at load.string.read (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug/lib/index.js:142:25)
    at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-load/index.js:23:44
    at walkAST (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-walk/index.js:13:26)
    at /home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-walk/index.js:21:16
    at Array.map (native)
    at walkAST (/home/rob/.nvm/versions/node/v5.12.0/lib/node_modules/pug-cli/node_modules/pug-walk/index.js:20:29)
```

**Comment by TimothyGu** [comment]
You don't have to specify `-b` in most cases. See [documentation](https://pugjs.org/language/includes.html):

> The path of the included file, if specified absolutely (e.g. `include /root.pug`), is resolved by prepending `options.basedir` to the file name provided. Otherwise, the path is relative to the current file being compiled.

**Comment by robbyoconnor** [comment]
not passing -b gave me the filename, thank you! Can I have the duncecap please?
