### ISSUE TITLE
Getting TypeError when trying to `include` a Pug partial

### ISSUE THREAD

**Issue by geoffdavis92** [pugjs/pug#2556]
```console
TypeError: Cannot read property 'replace' of undefined
   at before ([PATH_TO_MY_PROJECT]/node_modules/pug/node_modules/pug-linker/index.js:104:48)
   at walkAST ([PATH_TO_MY_PROJECT]/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:13:26)
   at [PATH_TO_MY_PROJECT]/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:21:16
   at Array.map (native)
   at walkAST ([PATH_TO_MY_PROJECT]/node_modules/pug/node_modules/pug-linker/node_modules/pug-walk/index.js:20:29)
   at applyIncludes ([PATH_TO_MY_PROJECT]/node_modules/pug/node_modules/pug-linker/index.js:102:10)
   at link ([PATH_TO_MY_PROJECT]/node_modules/pug/node_modules/pug-linker/index.js:21:9)
   at link ([PATH_TO_MY_PROJECT]/node_modules/pug/node_modules/pug-linker/index.js:37:18)
   at compileBody ([PATH_TO_MY_PROJECT]/node_modules/pug/lib/index.js:84:11)
   at Object.exports.compile ([PATH_TO_MY_PROJECT]/node_modules/pug/lib/index.js:164:16)
```

I am trying to create a simple default layout for an Express project. I've done this exact same thing before with Jade and Pug 1.0, but for some reason this is not working for me.

I'm extending a file, `layouts/default.pug`, which is including a file, `layouts/parts/head.pug`; I believe that the issue is stemming from including the `head.pug` file, as if I remove the include line, the page compiles fine. 

Folder Structure:
![views->index.pug,layouts->default.pug,parts->head.pug](http://image.prntscr.com/image/34a3777d6579403ca656478b0bfa8652.png)

index.pug:
```pug
extends layouts/default.pug
block frontmatter
	- var page = {}
	- page.title = 'Home'
block content
	h1 Home
```

layouts/default.pug:
```pug
include parts/head.pug
block content
```

layouts/parts/head.pug
```pug
block frontmatter
doctype html
head
	title
		if page.title
			#{page.title}
body
```

I've tried omitting the `.pug` file extensions on the `extend`/`include` lines and reordering the `block blockName` and `extend`/`include` lines, but nothing seems to be working.

**Comment by cesariux23** [comment]
use **pug@2.0.0-beta6**, see [pug-linker issue #13](https://github.com/pugjs/pug-linker/issues/13)
