### ISSUE TITLE
const, let in node v4

### ISSUE THREAD

**Issue by azappa** [pugjs/pug#2594]
Using pug with node@4 pug gives me error like `cannot use const / let in strict mode`.  Perhaps node5+ is the requirement for avoid errors?

**Comment by TimothyGu** [comment]
Pug doesn't use `let` or `const` in its own code. Check the stack trace.

**Comment by ForbesLindesay** [comment]
Could you paste the exact error in here?  If it's the error I've seen before it is actually the reverse of what you've posted here.  i.e. you can only use `let` and `const` in strict mode in some versions of node.  Ideally we would put templates into strict mode, but that would be a difficult breaking change to manage so it won't be soon.

**Comment by aMarCruz** [comment]
@azappa , node v4 don't allow `let`/`const` in strict mode, node v5+ does not have this limitation.

**Comment by choikwa** [comment]
I can provide a stack trace..
```
  myapp:server Listening on port 3000 +0ms

/express/myapp/node_modules/pug/node_modules/pug-parser/index.js:391
      const expr = this.parseExpr();
      ^^^^^
GET / 500 31.639 ms - 797
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/express/myapp/node_modules/pug/lib/index.js:17:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by choikwa** [comment]
created PR #2827
