### ISSUE TITLE
Error when there's unbuffered code at the top of an extending template

### ISSUE THREAD

**Issue by terrycloth** [pugjs/pug#2721]
I have a Pug template that extends a default template that I created for my static website project. In the extending template, I set a variable using a line of "unbuffered code" at the top of the file ( something like this:  `- var foo.bar = "string";` ). Pug seems to treat the unbuffered code as an a tag, as I get this error when compiling:

<samp>
/PATH/TO/MY/PROJECT/node_modules/pug-linker/index.js:7
  throw require('pug-error').apply(null, arguments);
  ^

Error: templates/posts.pug:5

<strong>Only named blocks and mixins can appear at the top level of an extending template</strong>
    at makeError (/PATH/TO/MY/PROJECT/node_modules/pug-error/index.js:32:13)
    at error (/PATH/TO/MY/PROJECT/node_modules/pug-linker/index.js:7:30)
    at addNode (/PATH/TO/MY/PROJECT/node_modules/pug-linker/index.js:34:9)
    at Array.forEach (native)
    at link (/PATH/TO/MY/PROJECT/node_modules/pug-linker/index.js:26:15)
    at link (/PATH/TO/MY/PROJECT/node_modules/pug-linker/index.js:37:18)
    at compileBody (/PATH/TO/MY/PROJECT/node_modules/pug/lib/index.js:171:9)
    at Object.exports.compile (/PATH/TO/MY/PROJECT/node_modules/pug/lib/index.js:243:16)
    at handleTemplateCache (/PATH/TO/MY/PROJECT/node_modules/pug/lib/index.js:216:25)
    at Object.exports.renderFile (/PATH/TO/MY/PROJECT/node_modules/pug/lib/index.js:418:10)
    at Object.&lt;anonymous&gt; (/PATH/TO/MY/PROJECT/build.js:364:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
</samp>

...This is possibly a duplicate of issue #2632? I considered commenting on that thread, but there the OP started by reporting an issue with code comments, and then by the end it seemed like maybe their bug report was invalid.

**Comment by ForbesLindesay** [comment]
This error message is exactly correct. You can only have named blocks and mixins at the top level of an extending template.  Unbuffered code is neither a named block, nor a mixin.  You can declare:

```pug
block variables
```

in your layout template.  Then you can put code in it using:

```pug
block variables
  - var foo.bar = "string";
```

in the child template.
