### ISSUE TITLE
events.js:160

### ISSUE THREAD

**Issue by badoubadou** [pugjs/pug#2736]
events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: code.replace is not a function

Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
 at deleteSemicolon (/Users/Sites/test/node_modules/phpjade/lib/phpjade.js:151:19)
    at Compiler.jade.Compiler.attrs (/Users/Sites/test/node_modules/phpjade/lib/phpjade.js:231:21)
    at Compiler.visitAttributes (/Users/Sites/test/node_modules/jade/lib/compiler.js:652:12)
    at Compiler.visitTag (/Users/Sites/test/node_modules/jade/lib/compiler.js:477:12)
    at Compiler.visitNode (/Users/Sites/test/node_modules/jade/lib/compiler.js:225:37)
    at Compiler.visit (/Users/Sites/test/node_modules/jade/lib/compiler.js:212:10)
    at Compiler.visitBlock (/Users/Sites/test/node_modules/jade/lib/compiler.js:295:12)
    at Compiler.visitNode (/Users/Sites/test/node_modules/jade/lib/compiler.js:225:37)
    at Compiler.visit (/Users/Sites/test/node_modules/jade/lib/compiler.js:212:10)
    at Compiler.compile (/Users/Sites/test/node_modules/jade/lib/compiler.js:66:10)

**Comment by strugee** [comment]
@badoubadou you need to provide us with the input that produces this error. Please also edit your issue title to something more descriptive (perhaps "TypeError: code.replace is not a function"?)

**Comment by akzhan** [comment]
This is bug not of pug itself (https://github.com/kurohara/phpjade/blob/master/lib/phpjade.js#L151)

Please move this ticket to https://github.com/kurohara/phpjade project.
