### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by nguyenquanit17** [pugjs/pug#2787]
Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
    at Object.exports.stringify (D:\_Project\nodejs\wrap\node_modules\jade\lib\utils.js:19:14)
    at Compiler.<anonymous> (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:685:87)
    at Array.forEach (native)
    at Compiler.attrs (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:665:11)
    at Compiler.visitAttributes (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:652:12)
    at Compiler.visitTag (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:477:12)
    at Compiler.visitNode (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:225:37)
    at Compiler.visit (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:212:10)
    at Compiler.visitBlock (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:295:12)
    at Compiler.visitNode (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:225:37)
    at Compiler.visit (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:212:10)
    at Compiler.visitBlock (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:295:12)
    at Compiler.visitNode (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:225:37)
    at Compiler.visit (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:212:10)
    at Compiler.visitTag (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:480:12)
    at Compiler.visitNode (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:225:37)
    at Compiler.visit (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:212:10)
    at Compiler.visitBlock (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:295:12)
    at Compiler.visitNode (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:225:37)
    at Compiler.visit (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:212:10)
    at Compiler.visitTag (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:480:12)
    at Compiler.visitNode (D:\_Project\nodejs\wrap\node_modules\jade\lib\compiler.js:225:37)

**Comment by ForbesLindesay** [comment]
Please update to the latest pug beta.
