### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by sdawson26** [pugjs/pug#2825]
This is so weird. I'm starting with this...
```
extends _layout.jade
block content
  section.section-padding
    .container
      h2.font-30.mb-30 TITLE
      .row
        .col-md-7 BODY
```

And I'm just adding one simple line of code that says 'hey' .. no special variables or any other tricks added (i've verified that the indentation is in place)
```
extends _layout.jade
block content
  section.section-padding
    .container
      h2.font-30.mb-30 TITLE
      .row
        .col-md-7 BODY
        .col-md-5 Hey
```

And suddenly everything stops working and it returns this error:
```
TypeError: Cannot read property 'apply' of undefined
    at /Users/shawn/Dev/website/node_modules/express/lib/router/index.js:635:14
    at IncomingMessage.next (/Users/shawn/Dev/website/node_modules/express/lib/router/index.js:260:14)
    at done (/Users/shawn/Dev/website/node_modules/express/lib/response.js:961:25)
    at Object.exports.renderFile (/Users/shawn/Dev/website/node_modules/pug/lib/index.js:420:14)
    at View.exports.__express [as engine] (/Users/shawn/Dev/website/node_modules/pug/lib/index.js:465:11)
    at View.render (/Users/shawn/Dev/website/node_modules/express/lib/view.js:128:8)
    at tryRender (/Users/shawn/Dev/website/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/Users/shawn/Dev/website/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/shawn/Dev/website/node_modules/express/lib/response.js:966:7)
    at /Users/shawn/Dev/website/pub/index.js:301:19

```

I've been able to correct the issue by reverting back to jade instead of pug. It's confusing that I'm being told that Jade is deprecated, yet the fact that this bug only happens with pug files is unfortunate.

**Comment by ForbesLindesay** [comment]
Make sure you are using the latest version of pug.  This does not contain enough info to diagnose and it looks like the bug might actually be in express, rather than pug.
