### ISSUE TITLE
I was told to post here 

### ISSUE THREAD

**Issue by JamesJansson** [pugjs/pug#2847]
jade@1.11.0

Error: The end of the string was reached with no closing bracket found.

Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
    at parseMax (...\node_modules\character-parser\index.js:26:13)
    at Object.buffer (...\node_modules\jade\lib\compiler.js:119:23)
    at Object.visitText (...\node_modules\jade\lib\compiler.js:523:10)
    at Object.visitNode (...\node_modules\jade\lib\compiler.js:225:37)
    at Object.visit (...\node_modules\jade\lib\compiler.js:212:10)
    at Object.visitBlock (...\node_modules\jade\lib\compiler.js:295:12)
    at Object.visitNode (...\node_modules\jade\lib\compiler.js:225:37)
    at Object.visit (...\node_modules\jade\lib\compiler.js:212:10)
    at Object.visitTag (...\node_modules\jade\lib\compiler.js:480:12)
    at Object.visitNode (...\node_modules\jade\lib\compiler.js:225:37)
    at Object.visit (...\node_modules\jade\lib\compiler.js:212:10)
    at Object.visitBlock (...\node_modules\jade\lib\compiler.js:295:12)
    at Object.visitNode (...\node_modules\jade\lib\compiler.js:225:37)
    at Object.visit (...\node_modules\jade\lib\compiler.js:212:10)
    at Object.visitBlock (...\node_modules\jade\lib\compiler.js:295:12)
    at Object.visitNode (...\node_modules\jade\lib\compiler.js:225:37)
    at Object.visit (...\node_modules\jade\lib\compiler.js:212:10)
    at Object.visitTag (...\node_modules\jade\lib\compiler.js:480:12)
    at Object.visitNode (...\node_modules\jade\lib\compiler.js:225:37)
    at Object.visit (...\node_modules\jade\lib\compiler.js:212:10)
    at Object.visitBlock (...\node_modules\jade\lib\compiler.js:295:12)
    at Object.visitNode (...\node_modules\jade\lib\compiler.js:225:37)

**Comment by ForbesLindesay** [comment]
Please update to the latest version of pug, and your issue should be fixed.
