### ISSUE TITLE
SyntaxError: Unexpected token (166:4) from Acorn/Acorn-globals

### ISSUE THREAD

**Issue by weirdestnerd** [pugjs/pug#2869]
**Pug Version:** 2.0.0-rc.4

**Node Version:** 8.3.0

**NPM Version:** 5.4.1

After updating npm, I keep getting this error:
```
SyntaxError: Unexpected token (166:4)
    at Parser.pp$4.raise (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp.semicolon (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:600:59)
    at Parser.pp$1.parseExpressionStatement (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1025:8)
    at Parser.pp$1.parseStatement (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:780:22)
    at Parser.pp$1.parseBlock (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1040:23)
    at Parser.pp$1.parseStatement (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:754:31)
    at Parser.pp$1.parseFor (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1057:20)
    at Parser.pp$1.parseForStatement (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:851:17)
    at Parser.pp$1.parseStatement (/Users/OluMac/Documents/WebDev/moxievr/dynamic/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:736:29)
```

The error happens after making a post request with ExpressJS. I have tried updating to latest versions of `acorn` and `acorn-globals`, but the error still persists. I opened an issue with `acorn`  [here](https://github.com/ternjs/acorn/issues/587#issuecomment-328756965) and it's not on acorn's end.

**Comment by droooney** [comment]
Could you post the Pug code, rendering which causes the error? It's hard to tell without any.

**Comment by weirdestnerd** [comment]
```JavaScript
app.post('/login', (req, res) => {
    // firebase_login() uses firebase-auth for authentication and callback is called on fulfilled Promise
    firebase_login(email, password, (error) => {
        if(error) return res.render('access')
        return res.render('dashboard')
   })
})
```
`dashboard.pug`
```JavaScript
doctype html
html
  head
    include includes/dashboard/head.pug
    style
      include includes/dashboard/dashboard.css
  body
    div(class='wrapper')
      include includes/dashboard/sidebar.pug
      div(class='main-panel')
        include includes/dashboard/nav.pug
```
`head.pug`
```
meta(charset="utf-8")
link(rel="apple-touch-icon" sizes="76x76" href="img/apple-icon.png")
link(rel="icon" type="image/png" href="img/favicon.png")
meta(http-equiv="X-UA-Compatible" content="IE=edge,chrome=1")

title Your Dashboard

meta(content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport')
meta(name="viewport" content="width=device-width")

//- Bootstrap core CSS
link(href="dashboard/css/bootstrap.min.css" rel="stylesheet")

//-  Material Dashboard CS
link(href="dashboard/css/material-dashboard.css" rel="stylesheet")

//-     Fonts and icons
link(href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet")
link(href='https://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css')
```
`sidebar.pug`
```JavaScript
div(class="sidebar" data-color="orange" data-image="img/sidebar-2.jpg")
  div(class="logo")
    a(href="/" class="simple-text")
      img(src="images/moxie-vr-logo.png" alt="")
  div(class="sidebar-wrapper")
    ul(class="nav")
      li
        //- (class="active")
        a(href="/dashboard")
          i(class="material-icons") dashboard
          p 
          | Dashboard
      li
        a(href="/dashboard_trainers")
          i(class="material-icons") directions_run
          p 
          | Trainers
      li
        a(href="/dashboard_videos")
          i(class="material-icons") videocam
          p 
          | Videos
```
`nav.pug`
```JavaScript
nav(class="gtco-nav" role="navigation")
  div(class="gtco-container")
    div(class="row")
      div(class="col-sm-2 col-xs-12")
        div(id="gtco-logo")
          a(href="/")
            img(src="images/moxie-vr-logo.png" alt="")
      div(class="col-xs-10 text-right menu-1")
        ul
          li
            a(href='/') Home
          li
            a(href="/trainers") Trainers
          li
            a(href="/about") About
          li
            a(href="/access") Try Beta
```
`

**Comment by droooney** [comment]
Have you found out the reason why this was happening?

**Comment by weirdestnerd** [comment]
Yeah. I incorrectly declared a Pug variable in a different file.

**Comment by anurupr** [comment]
if you can show how you got this error, it would be helpful

**Comment by weirdestnerd** [comment]
It’s not from the code I posted here. It was in a different file I referenced but I simply had a ‘val’ instead of ‘var’.

**Comment by jlbets123** [comment]
The same error happened to me on a different project. It was the same, "vat" instead of "var". Thank you mate, i went just to the point.

**Comment by ogrotten** [comment]
@weirdestnerd 

I had the exact same thing, but with `val` instead of `var` just like you. I had been trying to figure out what was wrong with my variable definition for over an hour before I saw your post.

I'll go ahead and say it: _always post your solution no matter how dumb it seems._ Without your solution who knows what I would have resorted to.

**Comment by jcoffland** [comment]
It really sucks that the line and column number reported by acorn.js has no relation to the pug file.  How do you find the correct line and column?

**Comment by Ricmo** [comment]
I got this same error today with a typo that used a dash instead of an equals sign for an attribute assignment:

example:      `#myid.hide.anotherclass(data-section-"step4")`
