### ISSUE TITLE
Object iterator and/or proxy is not callable

### ISSUE THREAD

**Issue by TheColorRed** [pugjs/pug#2934]
**Pug Version:** 2.0.0-rc.4

**Node Version:** 8.9.3

## Input JavaScript Values

```js
class Row {
  constructor() {
    this._row = {}
    return new Proxy(this, {
      get: function (target, prop) {
        return (<any>target)[prop] || target._row[prop] || ''
      }
    })
  }
}

class User {
  constructor() {
    this._items = []
    this.pointer = 0
    return new Proxy(this, {
      get: (target, prop) => {
        if (prop in target._items.row) {
          return target._items.row[prop]
        }
        return target[prop]
      }
    })
  }
  async queryDatabase(q) {
    this._items = await query.query(q) // returns an array of `Row` objects
    return this
  }
  next() {
    if (Array.isArray(this._items)) {
      if (this.pointer < this._items.length) {
        return { done: false, value: this._items[this.pointer++] }
      } else {
        this.pointer = 0
        return { done: true, value: undefined }
      }
    } else {
      return { done: true, value: this._items[0] }
    }
  }
  [Symbol.iterator]() {
    return this
  }
}

let carousel = new User().queryDatabase('select * from users limit 10 order by rand()')
pug.renderFile('input.pug', { carousel });
```

## Input Pug

```pug
each user in carousel
  - var avatar = user.avatar ? `background-image: url(${user.avatar})` : ''
  a(href=`/profile/${user.username}`)
    if (avatar.length > 0)
      span.card-header.padding-bottom-100-percent(style=`${avatar}`)
```

## Expected HTML

```html
<a href="/profile/UserA">
  <span class="card-header padding-bottom-100-percent" style="background-image: url(/avatars/userA.jpg)"></span>
</a>
<a href="/profile/UserB">
  <span class="card-header padding-bottom-100-percent" style="background-image: url(/avatars/userB.jpg)"></span>
</a>
<a href="/profile/UserC">
  <span class="card-header padding-bottom-100-percent" style="background-image: url(/avatars/userC.jpg)"></span>
</a>
```

## Actual HTML

```text
TypeError: /home/ryan/Documents/vscode/projects/dating/resources/views/pages/home.pug:7
    5|       .grid.padding-5.carousel.no-wrap
    6|         each user in carousel
  > 7|           - var avatar = user.avatar ? `background-image: url(${user.avatar})` : ''
    8|           a(href=`/profile/${user.username}`).card.cell.cell-2.cell-12-phone.cell-5-tablet.margin-right-10.black-text.black-text-hover
    9|             if (avatar.length > 0)
    10|               span.card-header.padding-bottom-100-percent(style=`${avatar}`)

Cannot read property 'avatar' of undefined
    at eval (eval at wrap (/home/ryan/Documents/vscode/projects/dating/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:123:19)
    at eval (eval at wrap (/home/ryan/Documents/vscode/projects/dating/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:176:4)
    at template (eval at wrap (/home/ryan/Documents/vscode/projects/dating/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:255:114)
    at Object.exports.renderFile (/home/ryan/Documents/vscode/projects/dating/node_modules/pug/lib/index.js:428:38)
    at Object.exports.renderFile (/home/ryan/Documents/vscode/projects/dating/node_modules/pug/lib/index.js:418:21)
    at View.exports.__express [as engine] (/home/ryan/Documents/vscode/projects/dating/node_modules/pug/lib/index.js:465:11)
    at View.render (/home/ryan/Documents/vscode/projects/dating/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/ryan/Documents/vscode/projects/dating/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/ryan/Documents/vscode/projects/dating/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/ryan/Documents/vscode/projects/dating/node_modules/express/lib/response.js:1008:7)
```

## Additional Comments

I have two classes, one is an object with an iterator to loop over an array property of `Row` objects. 
Both classes have Proxies on them to get items from within an object property.

When looping over `User` in Javascript this outputs each item:

```js
let carousel = new User().queryDatabase('select * from users limit 10 order by rand()')
for(let user of carousel) {
  console.log(user.avatar)
}
```

However, in pug this does not work.

I am not sure if the `next()` iterator isn't working or if the `Proxy` isn't working. Maybe both don't work.

**Comment by TheColorRed** [comment]
After messing around with my code base, it looks like it is running the proxy fine, but the iterator it is not utilizing.

**Comment by droooney** [comment]
`each in` does not work with iterators. If you want to pass an iterator to `each in` just do this:

```js
const iterator = new Iterator();

console.log(pug.renderFile('iterator.pug', { users: [...new Iterator()] }));
```

or do exactly the same in pug:

```pug
each user in [...users]
  span= user.name
```

**Comment by TheColorRed** [comment]
Ahh, okay I didn't know that could be done. Thanks!
