### ISSUE TITLE
Getting undefined but the object has the property

### ISSUE THREAD

**Issue by fzamperin** [pugjs/pug#2942]
**Pug Version:** v2.0.0-beta6

**Node Version:** v8.5.0

## Input JavaScript Values

```js
let data = {};
    let id = req.query.empresa;
    let empresa = await db.Empresa.findById(id, {
      include: [
        {
          model: db.Socio,
          required: false,
          as: 'representante'
        }
      ]
    });
    data.empresa = empresa;
    data.estados = await db.Estado.findAll();
    data.logradouros = await db.Logradouro.findAll();
    res.render('contador-formulario-empresa/empresa-representante', data);
```

## Input Pug

```pug
      .row
        .form-group.col-md-6
          label(for='nome') Nome Completo
          input.form-control(type='text',name='nome',value=empresa.representante.nome)
        .form-group.col-md-3
          label(for='profissao') Profissão
          input.form-control(type='text',name='profissao',value=empresa.representante.profissao)
        .form-group.col-md-3
          label(for='qualificacao') Qualificação
          select(name='qualificacao').form-control
            if empresa.tipo == 'EI'
              option(value="Empresário",selected=empressa.representante.qualificacao=='Empresário') Empresário
            if empresa.tipo == 'LTDA'
              option(value="Administrador",selected=empresa.representante.qualificacao=='Administrador') Administrador
              option(value="Sócio-administrador",selected=empresa.representante.qualificacao=='Sócio-administrador') Sócio-administrador
            if empresa.tipo == 'EIRELI'
              option(value="Administrador",selected=empresa.representante.qualificacao=='Administrador') Administrador
              option(value="Titular",selected=empresa.representante.qualificacao=='Titular') Titular
              option(value="Titular Pessoa Física Incapaz ou Relativamente Incapaz (Exeto Menor)",selected=empresa.representante.qualificacao=='Titular Pessoa Física Incapaz ou Relativamente Incapaz (Exeto Menor)') Titular Pessoa Física Incapaz ou Relativamente Incapaz (Exeto Menor)
              option(value="Titular Pessoa Física Menor (Assistido/Representado)",selected=empresa.representante.qualificacao=='Titular Pessoa Física Menor (Assistido/Representado)') Titular Pessoa Física Menor (Assistido/Representado)
              option(value="Titular Pessoa Física Residente ou Domiciliado no Exterior",selected=empresa.representante.qualificacao=='Titular Pessoa Física Residente ou Domiciliado no Exterior') Titular Pessoa Física Residente ou Domiciliado no Exterior
```

## Additional Comments

I'm trying to render this view, I go to the database via sequelize and then I get the empresa object, inside empresa object there is some info about the entity "Empresa" like representante that is another entity, the result object of this query is:

```json
{
   "bens":[

   ],
   "atuacao":[
      "Estabelecimento Fixo"
   ],
   "endereco":{
      "cep":"78080200",
      "logradourotipo":"Avenida",
      "logradouronome":" Nestor de Lara Pinto",
      "numero":"02",
      "complemento":"",
      "bairro":"Jardim das Palmeiras",
      "municipio":"Cuiabá",
      "uf":"MT"
   },
   "id":11,
   "nome1":"FS1",
   "nome2":"FS2",
   "nome3":"FS3",
   "titulo":"FS Solucoes",
   "tipo":"EI",
   "capital":"10000000",
   "integralizado":true,
   "capitalIntegralizadoBens":"",
   "capitalIntegralizadoDinheiro":"10000000",
   "capitalaIntegralizar":"",
   "capitalaIntegralizarData":null,
   "numeroiptu":"112233",
   "area":120,
   "areautilizada":80,
   "objeto":"Soluções para a vida",
   "faturamento":"1000000",
   "notas":"10",
   "funcionarios":"1",
   "enquadramento":"Empresa de pequeno porte (EPP)",
   "tributacao":"Simples Nacional",
   "status":"Aberto",
   "createdAt":"2018-01-22T11:53:07.000Z",
   "updatedAt":"2018-01-22T11:53:41.000Z",
   "ContadorId":7,
   "representanteId":17,
   "atividadeprincipalId":987,
   "DocumentoId":null,
   "representante":{
      "documento":{
         "tipo":"Registo Geral",
         "numero":"13423454",
         "orgao":"SSP",
         "uf":"MT"
      },
      "endereco":{
         "cep":"78080200",
         "logradourotipo":"Avenida",
         "logradouronome":" Nestor de Lara Pinto",
         "numero":"02",
         "complemento":"",
         "bairro":"Jardim das Palmeiras",
         "municipio":"Cuiabá",
         "uf":"MT"
      },
      "responsavel":{
         "tipo":"Registo Geral",
         "numero":"13423454",
         "orgao":"SSP",
         "uf":"MT",
         "nome":"Felipe Silva"
      },
      "id":17,
      "nome":"Felipe Silva",
      "email":"felipesilva@email.com",
      "telefone":"6599222299",
      "capital":null,
      "profissao":"Empresario",
      "qualificacao":"Empresário",
      "cpf":"46545168401",
      "nacionalidade":"Brasiliero",
      "sexo":"Masculino",
      "analfabeto":"0",
      "nascimento":"1990-10-22",
      "estadocivil":"solteiro",
      "regimecasamento":null,
      "mae":"Maria Silva",
      "pai":"João Silva",
      "tipoRepresentacao":null,
      "emancipadoDoc":null,
      "createdAt":"2018-01-22T11:51:38.000Z",
      "updatedAt":"2018-01-22T11:53:07.000Z",
      "CadastrotempId":null,
      "EmpresaId":11,
      "UsuarioId":null
   }
}
```

And I'm getting the following error:
```
TypeError: /home/nodeappsdesenv/facilcontador/views/contador-formulario-empresa/empresa-representante.pug:25
    23|           select(name='qualificacao').form-control
    24|             if empresa.tipo == 'EI'
  > 25|               option(value="Empresário",selected=empressa.representante.qualificacao=='Empresário') Empresário
    26|             if empresa.tipo == 'LTDA'
    27|               option(value="Administrador",selected=empresa.representante.qualificacao=='Administrador') Administrador
    28|               option(value="Sócio-administrador",selected=empresa.representante.qualificacao=='Sócio-administrador') Sócio-administrador

Cannot read property 'representante' of undefined
    at eval (eval at wrap (/home/nodeappsdesenv/facilcontador/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:204:94)
    at template (eval at wrap (/home/nodeappsdesenv/facilcontador/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:970:72)
    at Object.exports.renderFile (/home/nodeappsdesenv/facilcontador/node_modules/pug/lib/index.js:428:38)
    at Object.exports.renderFile (/home/nodeappsdesenv/facilcontador/node_modules/pug/lib/index.js:418:21)
    at View.exports.__express [as engine] (/home/nodeappsdesenv/facilcontador/node_modules/pug/lib/index.js:465:11)
    at View.render (/home/nodeappsdesenv/facilcontador/node_modules/express/lib/view.js:126:8)
    at tryRender (/home/nodeappsdesenv/facilcontador/node_modules/express/lib/application.js:639:10)
    at Function.render (/home/nodeappsdesenv/facilcontador/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/home/nodeappsdesenv/facilcontador/node_modules/express/lib/response.js:960:7)
    at router.get (/home/nodeappsdesenv/facilcontador/routes/contador.js:218:9)
    at <anonymous>
```
If you take a look at the view the object is used before this line without problems but at this line I'm getting undefined I tried everything. I dont't have a clue why this is happening. Thanks in advance.

**Comment by droooney** [comment]
I think you misspelled the word `empresa` there.
