### ISSUE TITLE
The end of the string reached with no closing bracket ) found.

### ISSUE THREAD

**Issue by jeffreycsun** [pugjs/pug#2951]
**Pug Version:** ^2.0.0-rc.4

**Node Version:** v8.1.4

**npm Version:** 5.3.0

**OS:** Windows 7 Professional SP1

## Input JavaScript Values

```js
const pug = require('pug')
const compiledFunction = pug.compileFile('./layouts/posts/pages/templates/default.pug')
```

## Input Pug

```pug
// layouts/posts/pages/templates/default.pug

doctype html
html
  include ../../partials/head

```

```pug
// layouts/posts/partials/head.pug

head
  meta(charset="utf-8")
  meta(name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no")
  include js
```

```pug
// layouts/posts/partials/js.pug

// highlight.js
script(src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js")

// init highlight.js
script.
  hljs.initHighlightingOnLoad();
  
// jquery
script(https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous")

// popper.js
script(src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous")

// Bootstrap 4
script(src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous")

// Dismiss expanded nav bar on click
script.
  $(document).on('click', function() { $('.collapse').collapse('hide'); });

```
## Error in node
I'm running this straight from the node REPL.
I just run ```node``` in my project directory, then input 
```js
const pug = require('pug')
const compiledFunction = pug.compileFile('./layouts/posts/pages/templates/default.pug')
```
and I get this error (I'm using compiledFunction7 because I've run it multiple times and can't reassign const compiledFunction - more to follow):
```
const compiledFunction7 = pug.compileFile('./layouts/posts/pages/templates/default.pug')
Error: layouts\posts\partials\js.pug:21:1
    19| script.
    20|   $(document).on('click', function() { $('.collapse').collapse('hide'); });
  > 21|
--------^

The end of the string reached with no closing bracket ) found.
    at makeError (C:\Users\gpxc86\staticgen\node_modules\pug-error\index.js:32:13)
    at Lexer.error (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:58:15)
    at Lexer.bracketExpression (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:234:14)
    at Lexer.attrs (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1011:24)
    at Lexer.callLexerFunction (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1319:23)
    at Lexer.advance (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1356:15)
    at Lexer.callLexerFunction (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1319:23)
    at Lexer.getTokens (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1375:12)
    at lex (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:12:42)
    at Object.lex (C:\Users\gpxc86\staticgen\node_modules\pug\lib\index.js:99:27)
```

### HOWEVER

When I edit js.pug to look like this (cutting the last 4 script tags):
```pug
// layouts/posts/partials/js.pug

// highlight.js
script(src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js")

// init highlight.js
script.
  hljs.initHighlightingOnLoad();

```

And run 
```
const compiledFunction10 = pug.compileFile('./layouts/posts/pages/templates/default.pug')
```
I get
```
undefined
```
Which I believe means it has been successful.

I have verified it by running:

```
console.log(compiledFunction10())
```
Which returns:
```
<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><!-- highlight.js--><script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script><!-- init highlight.js--><script>hljs.initHighlightingOnLoad();</script></head></html>
```

### CONTINUED TESTING

I swapped ```init highlight.js``` to the end of ```js.pug``` so that it looks like this:
```pug
// layouts/posts/partials/js.pug

// highlight.js
script(src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js")

// jquery
script(https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous")

// popper.js
script(src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous")

// Bootstrap 4
script(src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous")

// Dismiss expanded nav bar on click
script.
  $(document).on('click', function() { $('.collapse').collapse('hide'); });

// init highlight.js
script.
  hljs.initHighlightingOnLoad();
```
And I got this error instead:
```
Error: layouts\posts\partials\js.pug:22:1
    20| script.
    21|   hljs.initHighlightingOnLoad();
  > 22|
--------^

The end of the string reached with no closing bracket ) found.
    at makeError (C:\Users\gpxc86\staticgen\node_modules\pug-error\index.js:32:13)
    at Lexer.error (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:58:15)
    at Lexer.bracketExpression (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:234:14)
    at Lexer.attrs (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1011:24)
    at Lexer.callLexerFunction (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1319:23)
    at Lexer.advance (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1356:15)
    at Lexer.callLexerFunction (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1319:23)
    at Lexer.getTokens (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:1375:12)
    at lex (C:\Users\gpxc86\staticgen\node_modules\pug-lexer\index.js:12:42)
    at Object.lex (C:\Users\gpxc86\staticgen\node_modules\pug\lib\index.js:99:27)
```

I don't understand why the error isn't being thrown earlier, since all I did was swap the position of the script tags and just having two tags isn't throwing an error.

Thank you for any comments you might have on this matter.

## Additional Comments
Directory Structure:
```
layouts/
--posts/
----pages/
------templates/
--------default.pug
------page-that-will-inherit-from-default.pug
----partials/
------head.pug
------js.pug
```

**Comment by jeffreycsun** [comment]
Missing open quotes on jquery script source.

Thanks
