### ISSUE TITLE
Order of attributes matters when it includes a special character 

### ISSUE THREAD

**Issue by ceremcem** [pugjs/pug#2967]
**Pug Version:** 
pug version: 2.0.0-rc.2
pug-cli version: 1.0.0-alpha6

# Result is what is expected:

## Input Pug

```pug
doctype html
p({{extra-attributes}} hello="there") hey

```

## Expected HTML

```html
<!DOCTYPE html><p {{extra-attributes}} hello="there">hey</p>
```

## Actual HTML

```html
<!DOCTYPE html><p {{extra-attributes}} hello="there">hey</p>
```

# Problem:

## Input Pug

```pug
doctype html
p(hello="there" {{extra-attributes}}) hey

```

## Expected HTML

```html
<!DOCTYPE html><p hello="there" {{extra-attributes}}>hey</p>
```

## Error:

```bash
/usr/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:59
    throw err;
    ^

Error: test.pug:2:17
    1| doctype html
  > 2| p(hello="there" {{extra-attributes}}) hey
-----------------------^
    3| 

Syntax Error: Unexpected token
    at makeError (/usr/lib/node_modules/pug-cli/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/usr/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:58:15)
    at Lexer.assertExpression (/usr/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:86:12)
    at Lexer.attrs (/usr/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1089:18)
    at Lexer.callLexerFunction (/usr/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1319:23)
    at Lexer.advance (/usr/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1356:15)
    at Lexer.callLexerFunction (/usr/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1319:23)
    at Lexer.getTokens (/usr/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1375:12)
    at lex (/usr/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/usr/lib/node_modules/pug-cli/node_modules/pug/lib/index.js:99:27)

```

**Comment by ForbesLindesay** [comment]
This is because it's very hard to figure out where one attribute ends and another begins. You can separate them via a `,` or put the attribute key in `"` to indicate it may contain special characters. The only option we really have for fixing this is to disallow special characters like `.` and `{` at the start of attribute keys even when they are the first attribute in the list.

If someone wants to do that. I would gladly accept a pull request. 
The line of code that determines if we are at the end of an attribute value is https://github.com/pugjs/pug/blob/aebb1870313a50a4738045df5b916192a4a8d758/packages/pug-lexer/index.js#L1221

We should error (and suggest wrapping in `""`) on attributes that start with `characterParser.isPunctuator(character) && !quoteRe.test(character) && character !== ':'`.

**Comment by ceremcem** [comment]
Putting quotes (`"`) arount `{{...}}` is acceptable: 

```pug
doctype html
p(hello="there" "{{extra-attributes}}") hey
```

**Comment by ForbesLindesay** [comment]
I'd still like to fix this for the first attribute. It would be a breaking change, but it means we can give much better messaging and this question comes up quite a bit.

**Comment by drexpp** [comment]
Hello, I thought this would be a good contribution for one of my first PRs. Before commiting I would like to ask if the change I made would be good for this issue.

```
if((!characterParser.isPunctuator(str[x])` || quoteRe.test(str[x]) || str[x] === ':') && this.assertExpression(val, true)){
    done = true;
}else{
    this.error('INVALID_ATTRIBUTE_START', 'Invalid use of character "." or "{", wrap your attribute instead using double quotes ""');
}
``` 


Thanks a lot and sorry for having to review code twice I just wasn't sure if this was type of fix that was needed.

**Comment by drexpp** [comment]
Oh yeah sure I thought that it wasn't needed a message that long, so I will use yours, thanks.

I tested before any modification just as I cloned the repository ([result 1](https://i.gyazo.com/b046fb24c82882028068d1ecf0ae96f1.png))

Tested after adding a simple test just as below, to see if I could get an error related to the main issue of this topic  ([result 2](https://i.gyazo.com/d0f3c0b5f72fb3b1197ed43614573199.png))

`p(hello="var" {{extra-attributes}}) foo`

It seems like passed, which is weird or I am doing the test wrong.

So I moved on and tried to do the fix with the `else` statement and `this.error(..)`, but when I executed tests again it printed about 3-4 more errors than it did before (also its special character wrong is always `=`, because of str[0] in those examples), so I would like to ensure if things are good before trying any pull request or trying to fix whatever is wrong. ([result 3](https://i.gyazo.com/ab5c172452728678fd168ae262dabe58.png) [error picture](https://i.gyazo.com/44b2bd86cca08e9590223f75bac6471c.png))

Thanks for your time!

**Comment by ForbesLindesay** [comment]
This would be **much** easier to review as part of a pull request. Then I can see your code in context, along with the build output from travis.

You can probably fix the existing broken tests by running `yarn test -u` to update snapshots - you should ideally do this before making your change.

For your change, it looks like you're not testing exactly the right thing. The goal is to catch the case where the first "key" starts with special characters, not to test for the case where values start with special characters.

**Comment by drexpp** [comment]
Hello Forbes, I made the pull request it failed in some travis tests, probably related to my last message "[error picture](https://i.gyazo.com/44b2bd86cca08e9590223f75bac6471c.png)". I tried what I mentioned in the comment of the pull request, using a single `if statement` rather than `else` and it didn't print those errors, but not sure if it is the changed needed.

Thanks for your patience and time ~
