### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by zhancheng** [pugjs/pug#2978]
Module build failed: TypeError: Cannot read property 'start' of undefined

**Pug Version:** 2.0.0

**Node Version:** 8.0.0

when i build my project , i found this error in my console 'Module build failed: TypeError: Cannot read property 'start' of undefined' , then i go to the npmjs.org to check, i found the new version just release yesterday, so i thought it maybe a bug. please check it, thank you.

**Comment by ForbesLindesay** [comment]
Can you provide a stack trace? Or a code sample so we can reproduce?

**Comment by GabrielUlici** [comment]
it is because of pug-parser version 4.0.1

here is the stack trace:

TypeError: Cannot read property 'start' of undefined
    at Parser.parseExtends (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/node_modules/pug-parser/index.js:776:23)
    at Parser.parseExpr (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/node_modules/pug-parser/index.js:218:21)
    at Parser.parse (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/node_modules/pug-parser/index.js:112:25)
    at parse (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/lib/index.js:126:22)
    at Function.loadString [as string] (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/node_modules/pug-load/index.js:45:21)
    at compileBody (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/lib/index.js:243:16)
    at handleTemplateCache (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/lib/index.js:216:25)
    at Object.exports.renderFile (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/lib/index.js:428:10)
    at Object.exports.renderFile (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/lib/index.js:418:21)
    at View.exports.__express [as engine] (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/pug/lib/index.js:465:11)
    at View.render (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/express/lib/view.js:135:8)
    at tryRender (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/var/www/vhosts/billingapi/releases/20180308125755/node_modules/express/lib/response.js:1008:7)

**Comment by ForbesLindesay** [comment]
Can you confirm the version of pug-lexer and pug-parser (in `node_modules/pug-lexer/package.json` and `node_modules/pug-parser/package.json` respectively)

**Comment by GabrielUlici** [comment]
**now:**
"name": "pug-lexer",
  "version": "3.1.0",

"name": "pug-parser",
  "version": "4.0.1",


**when everything was working:**
"name": "pug-lexer",
  "version": "3.1.0",

 "name": "pug-parser",
  "version": "4.0.0",

**Comment by ForbesLindesay** [comment]
Ah, For some reason, you're getting an outdated version of pug-lexer.  If you're using `pug@2.0.0` you should get `pug-lexer@4.0.0`.  It was technically in correct for me to release pug-parser as 4.0.1, so I have released pug-parser 4.0.2 to revert the change and pug-parser 5.0.0 with the new code.

To fix your issue, either:

1. Update pug, pug-lexer and pug-parser to the latest versions
2. Update pug-parser to 4.0.2 (which is equivalent to pug-parser 4.0.0)

**Comment by GabrielUlici** [comment]
I have the "pug" version "2.0.0-rc.4" will updated to 2.0.1 and deploy again.

Thanks for the help.

**Comment by ForbesLindesay** [comment]
Yes, "2.0.0" or "2.0.1" should work fine.

**Comment by zhancheng** [comment]
thank u , it works
