### ISSUE TITLE
Unexpected Token after multiline JS

### ISSUE THREAD

**Issue by flxwu** [pugjs/pug#2985]
**Pug Version:** 2.0.1

**Node Version:** v8.9.4

## Input Pug
Starting at line 9, ending at line 23 (errors in line 23)
```pug
body
  - var data = [
  -          [{
  -                  title: 'Firebase 101',
  -                  desc: 'A Crash Course on Google\'s Cloud Computing Service Firebase',
  -                  link: 'http://presentations.flxwu.com/firebase101'
  -              },
  -              {
  -                  title: 'Crash Course Git',
  -                  desc: 'A Quick Introduction to modern Version Control using Git and Github.',
  -                  link: 'https://docs.google.com/presentation/d/1ue9GwJ9vSOf7HqejuaOvVJJVqGP3PWph_pXw6UQjM/edit?usp=sharing'
  -              }
  -          ],
  -      ];
 .container
```
## Error Output
When I try to compile using 
```
pug views/index.pug
```
it just returns
```

/usr/local/share/.config/yarn/global/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2490
  throw err
  ^

SyntaxError: Unexpected token (23:0)
    at Parser.pp$4.raise (/usr/local/share/.config/yarn/global/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected (/usr/local/share/.config/yarn/global/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp$3.parseExprAtom (/usr/local/share/.config/yarn/global/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2011:10)
    at Parser.pp$3.parseExprSubscripts (/usr/local/share/.config/yarn/global/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (/usr/local/share/.config/yarn/global/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (/usr/local/share/.config/yarn/global/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (/usr/local/share/.config/yarn/global/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (/usr/local/share/.config/yarn/global/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1750:19)
    ...
```
**However, when I put the full `data` declaration in one line, it works. Why?**

**Comment by ForbesLindesay** [comment]
Because debug mode (on by default unless `NODE_ENV === 'production'`) adds extra code between the lines. For multi-line JavaScript, you should use:

```pug
body
  -
    var x = [
      'multi',
      'line',
      'js',
    ];
  .container

**Comment by flxwu** [comment]
Okay, thank you very much :smile: @ForbesLindesay
