### ISSUE TITLE
Vue attributes starting with a colon break Pug mixins

### ISSUE THREAD

**Issue by wspringer** [pugjs/pug#3068]
**Pug Version:** 2.0.3

**Node Version:** 10.11.0

## Input JavaScript Values

```js
pug.renderFile('input.pug', {
});
```

## Input Pug

```pug
mixin m-card
  div&attributes(attributes)

+m-card(:src="www.google.com")
```

## Expected HTML

```html
<div :src="www.google.com"></div>
```

## Actual HTML

No HTML, but an error instead.

```bash
Error: Pug:4:10
    2|   div&attributes(attributes)
    3|
  > 4| +m-card(:src="www.google.com")
----------------^

Syntax Error: Unexpected token
    at makeError (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:59:15)
    at Lexer.assertExpression (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:87:12)
    at Lexer.call (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:857:16)
    at Lexer.callLexerFunction (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1456:23)
    at Lexer.advance (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1482:15)
    at Lexer.callLexerFunction (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1456:23)
    at Lexer.getTokens (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1512:12)
    at lex (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/Users/wilfred/.npm/_npx/74334/lib/node_modules/pug-cli/node_modules/pug/lib/index.js:99:27)
```

## Additional Comments

Interestingly, `+m-card.card(:src="www.google.com")` (mind the `.card` class) *does* work.

**Comment by droooney** [comment]
You can put the attribute name inside quotes: `":src"`.

**Comment by wspringer** [comment]
Hah, thanks for the tip! Still, am I wrong to think this behavior is a little surprising?

**Comment by wspringer** [comment]
Actually, it doesn't work:

```bash
Error: Pug:4:10
    2|   div&attributes(attributes)
    3|
  > 4| +m-card(":src"="www.google.com")
----------------^

Syntax Error: Assigning to rvalue
    at makeError (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:59:15)
    at Lexer.assertExpression (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:87:12)
    at Lexer.call (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:857:16)
    at Lexer.callLexerFunction (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1456:23)
    at Lexer.advance (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1482:15)
    at Lexer.callLexerFunction (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1456:23)
    at Lexer.getTokens (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:1512:12)
    at lex (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/Users/wilfred/.npm/_npx/81024/lib/node_modules/pug-cli/node_modules/pug/lib/index.js:99:27)
```

**Comment by droooney** [comment]
Aah, my bad, haven't noticed that there is only one pair of the parentheses. The first pair of the parentheses is the mixin parameters and the second one is what is assigned to `&attributes`. Try

```pug
+m-card()(:src="www.google.com")
```

if your mixin doesn't have parameters.

**Comment by lunelson** [comment]
@droooney I'd suggest you maintainers consider using a bot to close dead issues; there are quite a few, like this one, where a question has been answered correctly but the OP didn't close it 😬
