### ISSUE TITLE
Unescaped interpolation on new line not working

### ISSUE THREAD

**Issue by DzmVasileusky** [pugjs/pug#3133]
**Pug Version:** your version number here
2.0.3

**Node Version:** your version number here
8.11.4

## Input Pug

```pug
mixin someContainer(customTemplate)
    .container
        h1 Container
        !{customTemplate}

-var someTemplate = "<strong>Hello</strong>";

+someContainer(someTemplate)
```

## Expected HTML

```html
.container
    <h1>Container</h1>
    <strong>Hello</strong>
```

## Actual HTML

Not compiling with error 

unexpected text "!{cus"
    at makeError (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-lexer/index.js:59:15)
    at Lexer.fail (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-lexer/index.js:1441:10)
    at Lexer.advance (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-lexer/index.js:1501:15)
    at Lexer.callLexerFunction (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-lexer/index.js:1456:23)
    at Lexer.getTokens (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-lexer/index.js:1512:12)
    at lex (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug/lib/index.js:99:27)
    at Function.loadString [as string] (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-load/index.js:44:24)
    at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-load/index.js:31:27
    at walkAST (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-walk/index.js:23:18)
    at /Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-walk/index.js:104:20
    at Array.reduce (<anonymous>)
    at walkAndMergeNodes (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-walk/index.js:103:18)
    at walkAST (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-walk/index.js:37:19)
    at load (/Users/dzmvasilevsky/Work/TulaCo/webui/node_modules/pug-load/index.js:13:10)
ERROR in ./src/app/shared/components/property-tile-info/property-tile-info.pug (./node_modu

## Additional Comments

Works fine:
```pug
mixin someContainer(customTemplate)
    .container
        h1 Container
        div !{customTemplate}
```

**Comment by ForbesLindesay** [comment]
You can use the buffered code syntax:

https://pugjs.org/language/code.html#buffered-code

Or you can put your interpolation in piped text:

https://pugjs.org/language/plain-text.html#piped-text

Your example is not valid becuase the `!{` syntax and `#{` syntax are interpolation, which is only valid within plain text.

**Comment by zoldbogar** [comment]
I subscribe: unescaped interpolation does not work on new line. Luckily for me I have an html which does not care about new lines anywas...
What is shown as example in https://pugjs.org/language/interpolation.html#string-interpolation-unescaped
![image](https://user-images.githubusercontent.com/5602583/109817384-8d917680-7c3a-11eb-9e41-c0f0d72e5bf0.png)
will generate error if `!{riskyBusiness}` is put on a new line:
```
- var riskyBusiness = "<em>Some of the girls are wearing my mother's clothing.</em>";
.quote
  p Joel: 
  !{riskyBusiness}
```
