### ISSUE TITLE
TypeError: assets is not a function on line 15

### ISSUE THREAD

**Issue by ORESoftware** [pugjs/pug#3227]
**Pug Version:** your version number here

```
 "pug": "^2.0.3",
```

**Node Version:** your version number here

```
v12.16.1
```

I am getting this error:

```
/home/oleg/codes/channelmeter/channelmeter.com/node_modules/pug-runtime/index.js:228
    throw err;
    ^

TypeError: assets is not a function on line 15
    at eval (eval at wrap (/home/oleg/codes/channelmeter/channelmeter.com/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:487:78)
    at template (eval at wrap (/home/oleg/codes/channelmeter/channelmeter.com/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:737:114)
    at Object.<anonymous> (/home/oleg/codes/channelmeter/channelmeter.com/routes/index.js:37:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at loader (/home/oleg/codes/channelmeter/channelmeter.com/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/home/oleg/codes/channelmeter/channelmeter.com/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)

```

## Input JavaScript Values

```js
{

  const fullPath = getFullPath('home.pug');
  const templateStr = readViewPath(fullPath);
  const fn = pug.compile(templateStr, {
          filename: fullPath.slice(0,-4), 
          basedir: pugBaseDir
  });
  const html = fn({layout: false});

  router.get('/', setStandardHeaders(html.length), (req, res) => {
    res.send(html);
  });
}
```

please help

```
fullPath.slice(0,-4),   
// the above is meant to remove .pug from the filename, I assume that's necessary?
```

I also get another version of this error:

```
/home/oleg/codes/channelmeter/channelmeter.com/node_modules/pug-runtime/index.js:253
  throw err;
  ^

TypeError: /home/oleg/codes/channelmeter/channelmeter.com/views/home.pug:15
    13|     link(rel='stylesheet', href='https://fonts.googleapis.com/icon?family=Material+Icons')
    14|     script(src='https://kit.fontawesome.com/6753fd35b1.js')
  > 15|     link(rel='stylesheet', href=assets('marcom.css'))    <<<<< HERE
    16|     link(href="/favicon.ico", rel="shortcut icon")
    17|     if webpackManifest
    18|       script(type='text/javascript') window.webpackManifest = !{webpackManifest};

assets is not a function
    at eval (eval at wrap (/home/oleg/codes/channelmeter/channelmeter.com/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:487:78)
    at template (eval at wrap (/home/oleg/codes/channelmeter/channelmeter.com/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:737:114)

```

**Comment by ForbesLindesay** [comment]
Your pug template calls `assets`, but you are not passing in an `assets` function, hence the error.
