### ISSUE TITLE
@font-face CSS not recognized by pug

### ISSUE THREAD

**Issue by wetbadger** [pugjs/pug#3310]
**Pug Version:** 2.0.4

**Node Version:** v14.15.3

## Input JavaScript Values

```js
pug.render('index');
```

## Input Pug

```pug
style
    @font-face {font-family: Montserrat; src: url(public/fonts/Montserrat-Medium.ttf);}
    body {font-family: Monsterrat;}
```

## Expected HTML

```html
This text should be in Monsterrat.
But it's not.
```

## Actual HTML

```html
Error: /opt/lampp/htdocs/yuxinpei.com/views/received.pug:6:6
    4|    title Title!
    5|    style
  > 6|      @font-face {
------------^
    7|        font-family: Montserrat;
    8|        src: url(public/fonts/Montserrat-Medium.ttf);
    9|      }

unexpected text "@font"
    at makeError (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug-error/index.js:34:13)
    at Lexer.error (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug-lexer/index.js:62:15)
    at Lexer.fail (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug-lexer/index.js:1624:10)
    at Lexer.advance (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug-lexer/index.js:1689:12)
    at Lexer.callLexerFunction (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug-lexer/index.js:1642:23)
    at Lexer.getTokens (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug-lexer/index.js:1701:12)
    at lex (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug/lib/index.js:104:9)
    at Function.loadString [as string] (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug-load/index.js:53:24)
    at compileBody (/opt/lampp/htdocs/yuxinpei.com/node_modules/pug/lib/index.js:82:18)

```

## Additional Comments

So how would you use custom fonts on your .pug page?

**Comment by wetbadger** [comment]
Simple solution: you can link to an external stylesheet:

link(rel="stylesheet", href="style.css")

**Comment by phothinmg** [comment]
It is  not @font-face issue , pug render html file without `<meta>` in `<head>`.
To fix that ---

`meta.txt`

```
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

`index.pug`

```pug
html
    head
        include ./meta.txt    
        title bost-server
        link(rel='stylesheet', href='https://unpkg.com/myanmarwebfonts@1.0.3/myanmarwebfonts.css')
        link(rel='stylesheet',href='https://www.w3schools.com/w3css/4/w3.css')
       
    body
```

Its work for me to use Myanmar Fonts
