### ISSUE TITLE
PUG:UNEXPECTED_NODES_IN_EXTENDING_ROOT

### ISSUE THREAD

**Issue by sainagendra** [pugjs/pug#3380]
only named blocks and mixins can appear at the top level of an extending template
    at makeError (/Users/u1167798/Ws/smb_ui/node_modules/pug-error/index.js:34:13)
    at error (/Users/u1167798/Ws/smb_ui/node_modules/pug-linker/index.js:7:30)
    at addNode (/Users/u1167798/Ws/smb_ui/node_modules/pug-linker/index.js:37:9)
    at Array.forEach (<anonymous>)
    at link (/Users/u1167798/Ws/smb_ui/node_modules/pug-linker/index.js:29:15)
    at compileBody (/Users/u1167798/Ws/smb_ui/node_modules/pug/lib/index.js:194:9)
    at Object.exports.compile (/Users/u1167798/Ws/smb_ui/node_modules/pug/lib/index.js:269:16)
    at handleTemplateCache (/Users/u1167798/Ws/smb_ui/node_modules/pug/lib/index.js:242:25)
    at Object.exports.renderFile (/Users/u1167798/Ws/smb_ui/node_modules/pug/lib/index.js:454:10)
    at Object.<anonymous> (/Users/u1167798/Ws/smb_ui/server/index.js:238:27) {
  code: 'PUG:UNEXPECTED_NODES_IN_EXTENDING_ROOT',
  msg: 'Only named blocks and mixins can appear at the top level of an extending template',
  line: 4,
  column: 1,
  filename: 'dist/smb/index.pug',
  src: undefined,
  toJSON: [Function (anonymous)]
}

**Comment by webdiscus** [comment]
@sainagendra 
please format you code with indents, according Pug rules:

```pug
extends ./../../server/views/index.pug

block top
  base(href='/smb/')
  ...

block bottom
  script(src='runtime.f37c7fd1cd188f22.js', type='module')
  ...
```

**Comment by sainagendra** [comment]
the issue is this file is genrated in dist folder after the build so not sure how to resolve this issue
