### ISSUE TITLE
Sass Pug

### ISSUE THREAD

**Issue by PhiHung151** [pugjs/pug#3417]
I used: pug index.pug --watch --pretty 
but its doesn't work and show notifications:

Error: ENOENT: no such file or directory, lstat 'index.pug'
    at Object.lstatSync (node:fs:1593:3)
    at renderFile (C:\Users\Admin\AppData\Roaming\npm\node_modules\pug-cli\index.js:246:17)
    at tryRender (C:\Users\Admin\AppData\Roaming\npm\node_modules\pug-cli\index.js:209:5)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\pug-cli\index.js:149:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\pug-cli\index.js:148:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)

Is there anyone who can help me? Thanks

**Comment by thesohailjafri** [comment]
Can please elaborate the issue or write down the steps to reproduce @PhiHung151
