### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by WizzerWorks** [pugjs/pug#3434]
/usr/local/lib/node_modules/pug/node_modules/pug-runtime/index.js:285
  throw err;
  ^

TypeError: templates/mixins/itterate.pug:22
    20|             +itterate(item, item.title, obj)
    21|           else
  > 22|             - var schema = key.match(/^(properties)|(patternProperties)|(items)$/) ? obj : val
    23|             +itterate(item, name, schema)
    24|   else
    25|     dt

Cannot read property 'match' of undefined
    at Object.eval (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:172:18)
    at Object.pug_interp [as itterate] (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:178:4)
    at Object.eval (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:151:23)
    at Object.pug_interp [as itterate] (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:178:4)
    at Object.eval (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:174:23)
    at Object.pug_interp [as itterate] (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:178:4)
    at Object.eval (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:174:23)
    at Object.pug_interp [as itterate] (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:178:4)
    at Object.eval (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:174:23)
    at Object.pug_interp [as itterate] (eval at wrap (/usr/local/lib/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:178:4) {
  path: 'templates/mixins/itterate.pug'
}

**Pug Version:** your version number here

**Node Version:** v12.22.9

## Additional Comments

Using matic (https://github.com/mattyod/matic) with pug to process glTF 1.0 schemas.

**Comment by Davidiusdadi** [comment]
node 12 is long end of life :thinking:
