### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by macalinao** [pugjs/pug#681]
I haven't the slightest idea.

```
TypeError: /Users/simplyianm/Desktop/p/savagegames/savagegames-site/views/index.jade:19
    17|       h1 Savage Games News 
    18|         small from our 
  > 19|           a(href='http://savage-games.enjin.com/') Enjin site
    20|     
    21|     each entry in news
    22|       div

Cannot read property 'length' of null
    at eval at <anonymous> (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/jade/lib/jade.js:160:8)
    at eval at <anonymous> (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/jade/lib/jade.js:160:8)
    at Object.<anonymous> (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/jade/lib/jade.js:165:12)
    at ServerResponse._render (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/express/lib/view.js:425:21)
    at ServerResponse.render (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/express/lib/view.js:318:17)
    at /Users/simplyianm/Desktop/p/savagegames/savagegames-site/controllers/index_controller.coffee:42:18
    at /Users/simplyianm/Desktop/p/savagegames/savagegames-site/controllers/index_controller.coffee:32:14
    at /Users/simplyianm/Desktop/p/savagegames/savagegames-site/controllers/index_controller.coffee:37:12
    at callbacks (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/express/lib/router/index.js:272:11)
    at param (/Users/simplyianm/Desktop/p/savagegames/savagegames-site/node_modules/express/lib/router/index.js:246:11)
```

**Comment by samuray90** [comment]
![New Bitmap Image (4)](https://user-images.githubusercontent.com/47028775/77863544-26de2e80-721b-11ea-9c50-51f5d0485eb5.jpg)
